with (__oznamespace__) {
	extfun.setResLang("IDS_GANTT_YEAR", "年");
	extfun.setResLang("IDS_GANTT_QUARTER", "季度");
	extfun.setResLang("IDS_GANTT_MONTH", "月");
	extfun.setResLang("IDS_GANTT_DAY", "日");
	extfun.setResLang("IDS_BMT_START_DATA", "数据查询开始时间:");
	extfun.setResLang("IDS_BMT_END_DATA", "数据查询完成时间:");
	extfun.setResLang("IDS_BMT_START_BIND", "绑定起始时间:");
	extfun.setResLang("IDS_BMT_END_BIND", "绑定完成时间:");
	extfun.setResLang("IDS_BMT_START_LOAD", "模板生成开始时间:");
	extfun.setResLang("IDS_BMT_END_LOAD", "模板生成完成时间:");
	extfun.setResLang("IDS_BMT_START_EXPORT", "输出开始时间:");
	extfun.setResLang("IDS_BMT_END_EXPORT", "输出完成时间:");
	extfun.setResLang("IDS_MSG_ABOUT_FORCS", "\n注意: 该电脑程序受著作权法和国际协约的保护。\n\n非法复制及发布全部或部分 程序的行为，\n将受到民事及 刑事法的严厉追究，并成为起诉原由。");
	extfun.setResLang("IDS_MSG_LOADER_CREATE_TEMPLATE", "正在生成报表模板。");
	extfun.setResLang("IDS_MSG_LOADER_PREPARE_CONNECTION", "正在准备连接服务器。");
	extfun.setResLang("IDS_MSG_LOADER_CONNECTED", "成功连接服务器。");
	extfun.setResLang("IDS_MSG_LOADER_READ_REPORT_BYTE_FROM_REMOTE", "正在从服务器读取报表 Form。");
	extfun.setResLang("IDS_MSG_LOADER_READ_DATA_FROM_REMOTE", "正在从服务器读取数据。");
	extfun.setResLang("IDS_MSG_LOADER_LAUNCH_MODE", "报表模板生成信息");
	extfun.setResLang("IDS_MSG_LOADER_GENERATE_REPORT", "正在生成报表。");
	extfun.setResLang("IDS_MSG_MAIN_READY", "准备");
	extfun.setResLang("IDS_MSG_OZZ_OPEN", "正在打开 OZD 文件。");
	extfun.setResLang("IDS_MSG_MAIN_BINDING", "正在生成报表。");
	extfun.setResLang("IDS_MSG_MAIN_MSG", "信息");
	extfun.setResLang("IDS_ERR_LOADER_CANNOT_DECRYPT", "安全控件不符，无法打开文件。");
	extfun.setResLang("IDS_ERR_TITLE_PARAMETER", "参数");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_RGB", "该参数值为错误的 RGB 值。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_ZOOM", "用于参数的缩放值有错。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_CHILDCOUNT", "输入的下级报表数量设置出错。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_REFRESH", "刷新周期输入值无效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_RANGE", "PDF保存范围无效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_COPIES", "打印份数出错。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_PAGESINONE", "多页打印的每面打印的页数无效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_SPOOL_PAGES", "打印机后台打印值无效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEWIDTH", "设置了错误的窗口宽度。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEHEIGHT", "设置了错误的窗口高度。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEX", "设置了错误的窗 X 坐标。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEY", "设置了错误的窗 Y 坐标。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_ICON_SIZE", "设置的图标大小参数值无效。");
	extfun.setResLang("IDS_ERR_PARAM_NOT_INT", "参数值无法转换为数字。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_LINES", "错误的页面之间的行数。");
	extfun.setResLang("IDS_ERR_DLL_LOAD_FAILED", "JAR 库加载失败。\n程序可能无法正常运行。");
	extfun.setResLang("IDS_ERR_LOADER_SERVER_NO_MSG", "资源库不存在的信息代码。");
	extfun.setResLang("IDS_ERROR_SEARCH_CAN_NOT_FIND", "无法找到。");
	extfun.setResLang("IDS_FORBIDDEN_CHRS", ",./?_");
	extfun.setResLang("IDS_TEXT_ENCODING_ANSI", "ANSI");
	extfun.setResLang("IDS_TEXT_ENCODING_UNICODE", "Unicode");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_BASELINE_DATETIME", "server_baseline_datetime 参数值使用格式错误。");
	extfun.setResLang("IDS_NOTIFICAION_MESSAGEBOX", "通知");
	extfun.setResLang("IDS_NOTIFICAION_NODATA", "没有查询的数据");
	extfun.setResLang("IDS_OKSTRING", "确定");
	extfun.setResLang("IDS_CANCELSTRING", "取消");
	extfun.setResLang("IDS_YESSTRING", "是");
	extfun.setResLang("IDS_NOSTRING", "否");
	extfun.setResLang("IDS_MSG_END_MAKETEMPLATE", "");
	extfun.setResLang("IDS_MSG_ENDCHECKCONOPT", "连接选项确认完成。");
	extfun.setResLang("IDS_MSG_MAKETEMPLATE", "正在生成报表模板。");
	extfun.setResLang("IDS_MSG_STARTRCVFORM", "开始接收报表 Form。");
	extfun.setResLang("IDS_MSG_STARTRCVDATA", "开始接收数据模块。");
	extfun.setResLang("IDS_MSG_STARTBINDING", "开始绑定报表。");
	extfun.setResLang("IDS_MSG_ENDRCVFORM", "报表 Form 接收完成。");
	extfun.setResLang("IDS_MSG_ENDRCVDATA", "数据模块接收完成。");
	extfun.setResLang("IDS_MSG_STARTCHECKCONOPT", "开始连接选项确认。");
	extfun.setResLang("IDS_STATIC_PROGRESSBAR_OZ", "正在运行 OZ Report Viewer。");
	extfun.setResLang("IDS_MSG_START_DIRECT", "正在准备无预览打印或输出。");
	extfun.setResLang("IDS_MSG_IMAGEEXPORT_ERR", "The maximum size exceeds the manageable size.");
	extfun.setResLang("IDS_JAPAN_HALF1", "");
	extfun.setResLang("IDS_JAPAN_HALF2", "");
	extfun.setResLang("IDS_JAPAN_FULL1", "");
	extfun.setResLang("IDS_JAPAN_FULL2", "");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_QUALITY", "不正确的参数，质量值错误。");
	extfun.setResLang("ID_PAGE_LEFTMOST", "同一行中的第一页");
	extfun.setResLang("ID_PAGE_LEFT", "同一行中的上一页");
	extfun.setResLang("ID_PAGE_RIGHT", "同一行中的下一页");
	extfun.setResLang("ID_PAGE_RIGHTMOST", "同一行中的最后一页");
	extfun.setResLang("ID_ZOOM_RESET", "还原");
	extfun.setResLang("ID_ZOOM_IN", "放大");
	extfun.setResLang("ID_ZOOM_OUT", "缩小");
	extfun.setResLang("ID_PAGE_CONTROL", "页面导航");
	extfun.setResLang("ID_PAGE_TOP", "同一列中的第一页");
	extfun.setResLang("ID_PAGE_UP", "同一列中的上一页");
	extfun.setResLang("ID_PAGE_DOWN", "同一列中的下一页");
	extfun.setResLang("ID_PAGE_BOTTOM", "同一列中的最后一页");
	extfun.setResLang("ID_FILE_ETCSAVE", "保存");
	extfun.setResLang("ID_OPT_HCDATA", "保存数据");
	extfun.setResLang("IDS_OPT_BRL_SAVE", "BRL 保存");
	extfun.setResLang("ID_ZOOM_IN_OUT", "缩放比例");
	extfun.setResLang("ID_OZZ_OPEN", "打开");
	extfun.setResLang("ID_FILE_CLOSE", "关闭当前打开的文件。\n	关闭");
	extfun.setResLang("ID_FILE_PRINT", "打印当前打开的文件。\n	打印");
	extfun.setResLang("ID_APP_ABOUT", "产品 信息... ");
	extfun.setResLang("ID_APP_EXIT", "关闭");
	extfun.setResLang("ID_PAGE", "");
	extfun.setResLang("ID_PAGE_PREVIOUS", "上一页");
	extfun.setResLang("ID_REPORT_PRINT", "打印");
	extfun.setResLang("ID_VIEWER_HELP", "帮助");
	extfun.setResLang("ID_VIEWER_EXIT", "结束");
	extfun.setResLang("ID_BANKBOOK_PRINT", "存折打印机打印");
	extfun.setResLang("ID_ETC", "其他菜单");
	extfun.setResLang("ID_EXPORT_PDF", "保存为 PDF");
	extfun.setResLang("ID_EXPORT_XLS", "保存为 XLS");
	extfun.setResLang("ID_EXPORT_DOC", "保存为 DOC");
	extfun.setResLang("ID_EXPORT_DOCX", "保存为 DOCX");
	extfun.setResLang("ID_EXPORT_OZD", "保存为 OZD");
	extfun.setResLang("ID_EXPORT_HTML", "保存为 HTML");
	extfun.setResLang("ID_EXPORT_PPT", "保存为 PPT");
	extfun.setResLang("ID_EXPORT_SVG", "保存为 SVG");
	extfun.setResLang("ID_EXPORT_TXT", "保存为 TXT");
	extfun.setResLang("ID_EXPORT_CSV", "保存为 CSV");
	extfun.setResLang("ID_EXPORT_TIF", "保存为 TIF");
	extfun.setResLang("ID_EXPORT_JPG", "保存为 JPG");
	extfun.setResLang("ID_EXPORT_HML", "保存为 HML");
	extfun.setResLang("ID_EXPORT_HML97", "保存为 HWP");
	extfun.setResLang("ID_EXPORT_HWPX", "保存为 HWPX");
	extfun.setResLang("ID_EXPORT_ODT", "保存为 ODT");
	extfun.setResLang("ID_EXPORT_MAIL", "发送邮件");
	extfun.setResLang("ID_SEARCH_PARAM", "查询");
	extfun.setResLang("ID_EXPORT_MHT", "保存为 MHT");
	extfun.setResLang("ID_EXPORT_PNG", "保存为 PNG");
	extfun.setResLang("ID_EXPORT_GIF", "保存为 GIF");
	extfun.setResLang("ID_ZOOM_SINGLEPAGE_FITTOFRAME", "按适合窗口单页");
	extfun.setResLang("ID_ZOOM_SINGLEPAGECONTINUOUS_FITTOWIDTH", "按适合宽度单页连续");
	extfun.setResLang("ID_EXPORT_NXL", "保存为 NXL");
	extfun.setResLang("ID_EXPORT_CELL", "保存为 CELL");
	extfun.setResLang("ID_OPT_REFRESH", "刷新");
	extfun.setResLang("ID_OPT_LABEL", "添加 Memo");
	extfun.setResLang("ID_OPT_IMAGE", "Add image");
	extfun.setResLang("ID_OPT_LINE", "添加直线");
	extfun.setResLang("ID_OPT_ARROW", "添加箭头");
	extfun.setResLang("ID_OPT_RECTANGLE", "添加矩形");
	extfun.setResLang("ID_OPT_CIRCLE", "添加椭圆");
	extfun.setResLang("ID_OPT_CHECKMARK", "Add checkmark");
	extfun.setResLang("ID_PAGE_PREVIOUSMOST", "第一页");
	extfun.setResLang("ID_PAGE_CURRENTPAGE", "");
	extfun.setResLang("ID_PAGE_TOTALPAGE", "");
	extfun.setResLang("ID_PAGE_NEXT", "下一页");
	extfun.setResLang("ID_PAGE_NEXTMOST", "最后一页");
	extfun.setResLang("ID_ZOOM_INVERSEPAPER", "更改纸张方向");
	extfun.setResLang("ID_REPORT_CLOSE", "关闭");
	extfun.setResLang("ID_REPORT_CLOSEALL", "全部关闭");
	extfun.setResLang("ID_OPT_PARAMETERS", "输入参数");
	extfun.setResLang("ID_OPT_SEARCH", "查找...");
	extfun.setResLang("ID_VIEW_PAGESETUP", "页面设置");
	extfun.setResLang("ID_VIEW_REPORT_EXPLORER", "显示报表树");
	extfun.setResLang("ID_CLOSE_REPORT_EXPLORER", "Close the tree");
	extfun.setResLang("ID_VIEW_REPORT_THUMBNAIL", "显示缩略图");
	extfun.setResLang("ID_CLOSE_REPORT_THUMBNAIL", "Close the thumbnail");
	extfun.setResLang("ID_EXPORT_XLSX", "保存为 XLSX");
	extfun.setResLang("IDS_MSG_PRINT_JOB_SUCCESS", "输出成功。");
	extfun.setResLang("IDS_MESSAGE_COPY_CLIPBOARD", "已经复制到了剪贴板上 。");
	extfun.setResLang("ID_VIEW_NORMAL", "实际大小");
	extfun.setResLang("ID_VIEW_FITTOFRAME", "适合窗口");
	extfun.setResLang("ID_VIEW_FITTOWIDTH", "适合宽度");
	extfun.setResLang("ID_VIEW_FITTOCONTENTS", "适合可见");
	extfun.setResLang("ID_VIEW_PRINTSIZE", "打印大小");
	extfun.setResLang("ID_VIEW_SINGLE_PAGE", "单页");
	extfun.setResLang("ID_VIEW_SINGLE_PAGE_CONTINUOUS", "单页连续");
	extfun.setResLang("ID_VIEW_DOUBLE_PAGE", "两页");
	extfun.setResLang("ID_VIEW_DOUBLE_PAGE_CONTINUOUS", "两页连续");
	extfun.setResLang("ID_VIEW_CONTINUOUS", "连续");
	extfun.setResLang("ID_SCREENTOOL_HAND", "手形工具");
	extfun.setResLang("ID_SCREENTOOL_EDIT", "编辑模式");
	extfun.setResLang("ID_SCREENTOOL_TEXTSELECT", "文本选择模式");
	extfun.setResLang("ID_SCREENTOOL_MULTISCREENGUIDE", "Guide mode");
	extfun.setResLang("ID_MENU_SAVEASIMAGE", "图片另存为...");
	extfun.setResLang("ID_MENU_SAVEASAUDIO", "将音频另存为...");
	extfun.setResLang("ID_MENU_INITIALIZEINPUTDATA", "初始化输入数据");
	extfun.setResLang("ID_MENU_DELETE", "删除");
	extfun.setResLang("ID_MENU_EDIT", "更改属性");
	extfun.setResLang("ID_MENU_DONOTPRINT", "限制打印");
	extfun.setResLang("ID_MENU_CHANGE_LABEL", "转为标签");
	extfun.setResLang("ID_MENU_CHANGE_IMAGE", "转为图片");
	extfun.setResLang("ID_MENU_CHANGE_BARCODE", "转为条码");
	extfun.setResLang("ID_MENU_CHANGE_PDF417", "转为 PDF417 条码");
	extfun.setResLang("ID_MENU_CHANGE_HTML", "转为 HTML");
	extfun.setResLang("ID_MENU_CHANGE_QRBARCODE", "转为 QR 条码");
	extfun.setResLang("ID_MENU_CHANGE_DATAMATRIX", "转为 DataMatrix 条码");
	extfun.setResLang("ID_MENU_CHARTEDIT", "可旋转");
	extfun.setResLang("IDS_MSG_COMP_EDIT", "属性编辑");
	extfun.setResLang("IDS_MSG_COMP_MOVE", "移动");
	extfun.setResLang("IDS_MSG_COMP_INPUT", "输入");
	extfun.setResLang("IDS_MSG_COMP_LINK", "链接");
	extfun.setResLang("IDS_MSG_COMP_POSSIBLE", "允许");
	extfun.setResLang("IDS_MSG_COMP_IMPOSSIBLE", "不可能");
	extfun.setResLang("IDS_MSG_COMP_NAME_RECTANGLE", "矩形");
	extfun.setResLang("IDS_MSG_COMP_NAME_ELLIPSE", "椭圆");
	extfun.setResLang("IDS_MSG_COMP_NAME_LINE", "直线");
	extfun.setResLang("IDS_MSG_COMP_NAME_ARROW", "箭头");
	extfun.setResLang("IDS_MSG_COMP_NAME_CHART", "图表");
	extfun.setResLang("IDS_MSG_COMP_NAME_MEMO_LABEL", "Memo 标签");
	extfun.setResLang("IDS_MSG_COMP_NAME_LABEL", "标签");
	extfun.setResLang("IDS_MSG_COMP_NAME_BARCODE", "条码");
	extfun.setResLang("IDS_MSG_COMP_NAME_BARCODE2", "二维条码");
	extfun.setResLang("IDS_MSG_COMP_NAME_IMAGE", "图片");
	extfun.setResLang("IDS_MSG_OUTPUT_INFO", "信息");
	extfun.setResLang("IDS_MSG_OUTPUT_DEBUG", "验证");
	extfun.setResLang("IDS_MSG_OUTPUT_ERROR", "错误");
	extfun.setResLang("IDS_MSG_OUTPUT_ALL", "全部");
	extfun.setResLang("IDS_MSG_COMP_NAME_MEMO_CHECKMARK", "CheckMark");
	extfun.setResLang("IDS_OZFONT_PLAIN", "常规");
	extfun.setResLang("IDS_OZFONT_ITALIC", "倾斜");
	extfun.setResLang("IDS_OZFONT_BOLD", "加粗");
	extfun.setResLang("IDS_OZFONT_BOLDITALIC", "加粗倾斜");
	extfun.setResLang("IDS_DYN_CENTER", "中间");
	extfun.setResLang("IDS_DYN_LEFT", "左");
	extfun.setResLang("IDS_DYN_RIGHT", "右");
	extfun.setResLang("IDS_DYN_TOP", "上");
	extfun.setResLang("IDS_DYN_BOTTOM", "下");
	extfun.setResLang("IDS_DYN_NONE", "无");
	extfun.setResLang("IDS_DYN_IMG_NORMAL", "一般");
	extfun.setResLang("IDS_DYN_IMG_CENTER", "中间");
	extfun.setResLang("IDS_DYN_IMG_FIT", "固定");
	extfun.setResLang("IDS_DYN_IMG_TILE", "TILE");
	extfun.setResLang("IDS_DYN_IMG_FITBYWIDTH", "横向固定");
	extfun.setResLang("IDS_DYN_IMG_FITBYHEIGHT", "纵向固定");
	extfun.setResLang("IDS_DYN_IMG_ISOTROPIC", "同一比例");
	extfun.setResLang("IDS_DYN_IMG_TOPCENTER", "靠上、居中");
	extfun.setResLang("IDS_DYN_IMG_TOPRIGHT", "靠上、居中");
	extfun.setResLang("IDS_DYN_IMG_MIDDLELEFT", "居中、靠左");
	extfun.setResLang("IDS_DYN_IMG_MIDDLERIGHT", "居中、向右");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMLEFT", "靠下、靠左");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMCENTER", "靠下、居中");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMRIGHT", "靠下、靠右");
	extfun.setResLang("IDS_DYN_IMG_FITBYWIDTH_CENTER", "横向固定、居中");
	extfun.setResLang("IDS_DYN_IMG_FITBYHEIGHT_CENTER", "纵向固定、居中");
	extfun.setResLang("IDS_DYN_IMG_ISOTROPIC_CENTER", "同一比例、居中");
	extfun.setResLang("IDS_DYN_TRUE", "是");
	extfun.setResLang("IDS_DYN_FALSE", "不是");
	extfun.setResLang("IDS_DYN_HORIZONTAL", "水平");
	extfun.setResLang("IDS_DYN_VERTICAL", "垂直");
	extfun.setResLang("IDS_DYN_SHAPE_SLASH", "减少");
	extfun.setResLang("IDS_DYN_SHAPE_BACKSLASH", "逆减");
	extfun.setResLang("IDS_QRENCODING_UTF8", "UTF-8");
	extfun.setResLang("IDS_QRENCODING_ANSI", "ANSI");
	extfun.setResLang("IDS_QRECC_L", "L");
	extfun.setResLang("IDS_QRECC_M", "M");
	extfun.setResLang("IDS_QRECC_Q", "Q");
	extfun.setResLang("IDS_QRECC_H", "H");
	extfun.setResLang("IDS_VERIFYQRCODE_NOTPRINTED", "这份文档不是打印件。为了确认是否被篡改，请扫描打印文档上的 QRCode。");
	extfun.setResLang("IDS_NO_LINE_START", "!),.:;?]}¨•ˇˉ―‖’”…∶、。〃々〉》」』】〕〗！＂＇），．：；");
	extfun.setResLang("IDS_NO_LINE_END", "([{•‘“〈《「『【〔〖（．［｛￡￥");
	extfun.setResLang("IDS_MSG_OVERWRITE", "文件已存在。\n要替换它吗？");
	extfun.setResLang("IDS_MSG_SAVE", "保存");
	extfun.setResLang("ID_PAGE_PREVIOUS2", "前一页");
	extfun.setResLang("ID_PAGE_NEXT2", "下一页");
	extfun.setResLang("ID_ZOOM_RESET2", "还原");
	extfun.setResLang("ID_ZOOM_IN2", "放大");
	extfun.setResLang("ID_ZOOM_OUT2", "缩小");
	extfun.setResLang("ID_MENU_DONOTPRINT2", "打印");
	extfun.setResLang("ID_MENU_CHARTEDIT2", "退出编辑模式");
	extfun.setResLang("IDS_PRINT_RANGE_ERROR", "错误的打印范围。");
	extfun.setResLang("IDS_PRINT_RANGE_EMPTY", "未输入打印范围。");
	extfun.setResLang("IDS_EXCEL_RANGE_ERROR", "错误的行范围。");
	extfun.setResLang("IDS_EXCEL_RANGE_EMPTY", "未输入行范围。");
	extfun.setResLang("IDS_HTML_VERSION", "None");
	extfun.setResLang("IDC_INVALID_PASSWORD", "因为设置不允许的密码文字所以保存时不进行密码保护.");
	extfun.setResLang("ID_COMMENT_HIDE", "输入模式");
	extfun.setResLang("ID_COMMENT_PEN", "画笔");
	extfun.setResLang("ID_COMMENT_HPEN", "荧光笔");
	extfun.setResLang("ID_COMMENT_CLEAR", "全部删除");
	extfun.setResLang("ID_COMMENT_SIZE1", "粗细");
	extfun.setResLang("ID_COMMENT_SIZE10", "粗细");
	extfun.setResLang("ID_COMMENT_SIZE18", "粗细");
	extfun.setResLang("ID_COMMENT_PENCOLOR1", "颜色");
	extfun.setResLang("ID_COMMENT_PENCOLOR2", "颜色");
	extfun.setResLang("IC_COMMENT_COLOR3", "颜色");
	extfun.setResLang("ID_COMMENT_PENCOLOR3", "颜色");
	extfun.setResLang("ID_COMMENT_ERASERPEN", "橡皮擦");
	extfun.setResLang("ID_SCREENTOOL_COMMENT", "注释模式");
	extfun.setResLang("ID_COMMENT_PENCOLOR4", "颜色");
	extfun.setResLang("ID_COMMENT_PENCOLOR5", "颜色");
	extfun.setResLang("ID_COMMENT_PENCOLOR6", "颜色");
	extfun.setResLang("ID_COMMENT_DRAW_BORDER", "Draw border");
	extfun.setResLang("ID_COMMENT_FILL_BACKGROUND", "Fill background");
	extfun.setResLang("IDS_COMMENT_PEN_TITLE", "粗细 & 颜色");
	extfun.setResLang("IDS_COMMENT_HPEN_TITLE", "荧光笔粗细 & 颜色");
	extfun.setResLang("IDS_REMOVE_COMMENT", "是否删除所有注释？");
	extfun.setResLang("IDS_COMMENT_PEN", "");
	extfun.setResLang("IDS_COMMENT_HPEN", "");
	extfun.setResLang("IDS_COMMENT_REMOVE_ALL", "");
	extfun.setResLang("IDS_COMMENT_DRAW_BORDER_TITLE", "Border thickness && color");
	extfun.setResLang("IDS_COMMENT_FILL_BACKGROUND_TITLE", "Background color");
	extfun.setResLang("ID_TEXT_COPY", "复制");
	extfun.setResLang("ID_TEXT_SELECT_ALL", "全部选择");
	extfun.setResLang("ID_TEXT_DESELECT_ALL", "解除全部选择");
	extfun.setResLang("ID_START_EDITING", "Start Input");
	extfun.setResLang("ID_END_EDITING", "End Input");
	extfun.setResLang("ID_COPYINPUTDATA_JSON", "复制输入数据 (json)");
	extfun.setResLang("ID_COPY_PROCESSOR_ID", "Processor ID 数据 ");
	extfun.setResLang("IDS_MSG_PROGRESS_BINDING", "正在绑定报表.");
	extfun.setResLang("ID_MENU_SAVETABLEASPNG", "表格保存 (PNG)...");
	extfun.setResLang("ID_MENU_SAVETABLEASHTML", "表格保存 (HTML)...");
	extfun.setResLang("ID_MENU_SHOW_SAVED_HISTORY", "保存历史查询");
	extfun.setResLang("ID_HISTORY_SAVED", "保存历史");
	extfun.setResLang("ID_HISTORY_DETAIL", "项目别详细历史");
	extfun.setResLang("ID_HISTORY_BACK", "以前");
	extfun.setResLang("ID_HISTORY_REVERT", "Revert");
	extfun.setResLang("ID_HISTORY_COMPLETE", "完成");
	extfun.setResLang("IDS_BMT_START_SVG_BIND", "开始绑定:");
	extfun.setResLang("IDS_BMT_SVG_BINDING", "绑定中:");
	extfun.setResLang("IDS_BMT_END_SVG_BIND", "结束绑定:");
	extfun.setResLang("IDS_MSG_LOADER_READ_PAGE_FROM_REMOTE", "正在从服务器读取数据。");
	extfun.setResLang("ID_OPT_SHOWCONSOLE", "查看控制台...");
	extfun.setResLang("IDS_MSG_SCAN_ID_FAIL", "The ID card image cannot be recognized. Click the shoot button to shoot again.");
	extfun.setResLang("IDS_OPT_SAVEAS_DEFAULT", "基本选项");
	extfun.setResLang("IDS_OPT_SAVEAS", "保存选项");
	extfun.setResLang("IDS_OPT_SAVE_WAY_TXT", "Save report after binding per one page/pages.");
	extfun.setResLang("IDS_OPT_SAVE_WAY_ONEPAGE", "Save Per OnePage");
	extfun.setResLang("IDS_OPT_SAVE_WAY_EACHPAGE", "Save Per Pages");
	extfun.setResLang("IDS_OPT_SAVE_WAY", "保存方式");
	extfun.setResLang("IDS_OPT_SAVE_ACTION", "Action");
	extfun.setResLang("IDS_OPT_SAVE_MULTIDOC", "多文档");
	extfun.setResLang("IDS_OPT_SAVE_AREA", "保存范围");
	extfun.setResLang("IDS_OPT_SAVE_COMPONENT", "组件");
	extfun.setResLang("IDS_OPT_SAVE_LINK_INFO", "保存链接");
	extfun.setResLang("IDS_OPT_ACTION_AFTER_SAVE", "Action after save");
	extfun.setResLang("IDS_OPT_SAVE_ONEFILE", "单文档保存");
	extfun.setResLang("IDS_OPT_SAVE_ALLFILE", "多文档保存");
	extfun.setResLang("IDS_OPT_ALLPAGE", "全部");
	extfun.setResLang("IDS_OPT_CURRENTPAGE", "当前页");
	extfun.setResLang("IDS_OPT_SELECTEDPAGE", "选定页");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE", "自定义 : ");
	extfun.setResLang("IDS_OPT_COMPONENT_LABEL", "指定要保存的组件");
	extfun.setResLang("IDS_OPT_LABEL", "标签");
	extfun.setResLang("IDS_OPT_IMAGE", "图片");
	extfun.setResLang("IDS_OPT_BARCODE", "条形码");
	extfun.setResLang("IDS_OPT_PDF417", "PDF417 码");
	extfun.setResLang("IDS_OPT_QR_BARCODE", "QR 码");
	extfun.setResLang("IDS_OPT_HTML", "HTML");
	extfun.setResLang("IDS_OPT_CHART", "图表");
	extfun.setResLang("IDS_OPT_LINE", "直线");
	extfun.setResLang("IDS_OPT_CIRCLE", "椭圆");
	extfun.setResLang("IDS_OPT_RECTANGLE", "矩形");
	extfun.setResLang("IDS_OPT_ARROW", "箭头");
	extfun.setResLang("IDS_OPT_URL_LINK", "URL链接");
	extfun.setResLang("IDS_OPT_LIST_LINK", "目录链接");
	extfun.setResLang("IDS_OPT_PDF_SAVE", "PDF 保存选项");
	extfun.setResLang("IDS_OPT_DOC_IMFOR", "文档信息");
	extfun.setResLang("IDS_OPT_OPEN_PROTECT", "限制打开");
	extfun.setResLang("IDS_OPT_EDIT_PROTECT", "限制修改");
	extfun.setResLang("IDS_OPT_USER_RIGHT", "文档限制");
	extfun.setResLang("IDS_OPT_TITLE", "标题");
	extfun.setResLang("IDS_OPT_WRITER", "作者");
	extfun.setResLang("IDS_OPT_SUBJECT", "主题");
	extfun.setResLang("IDS_OPT_KEYWORD", "关键字");
	extfun.setResLang("IDS_OPT_APPLICATION", "应用程序");
	extfun.setResLang("IDS_OPT_USER_PW", "打开口令");
	extfun.setResLang("IDS_OPT_USER_PW_CONFIRM", "确认打开口令");
	extfun.setResLang("IDS_OPT_MASTER_PW", "修改口令");
	extfun.setResLang("IDS_OPT_MASTER_PW_CONFIRM", "确认修改口令");
	extfun.setResLang("IDS_OPT_PRINT_PERMIT", "允许打印");
	extfun.setResLang("IDS_OPT_CONTENTS_COPY", "允许内容复制");
	extfun.setResLang("IDS_OPT_SAVEIMG_TOCHART", "将图表保存为图片");
	extfun.setResLang("IDS_OPT_FONT_INCLUDE", "폰트 포함");
	extfun.setResLang("IDS_OPT_PRINT", "打印");
	extfun.setResLang("IDS_OPT_PRINT_COUNT", "打印份数");
	extfun.setResLang("IDS_OPT_PRINT_SCOPE", "打印范围");
	extfun.setResLang("IDS_OPT_PRINT_RULE", "打印方式");
	extfun.setResLang("IDS_OPT_COUNT", "份");
	extfun.setResLang("IDS_OPT_PRINT_ONEPAGE", "逐份打印");
	extfun.setResLang("IDS_OPT_PRINT_ALL_REPORT", "打印所有文件");
	extfun.setResLang("IDS_OPT_ALL", "全部");
	extfun.setResLang("IDS_OPT_CHOOSE_PAGE", "自定义");
	extfun.setResLang("IDS_OPT_PRINT_FITTOPAGE", "按纸张大小缩放");
	extfun.setResLang("IDS_OPT_DEVIDE_PRINT", "分割打印");
	extfun.setResLang("IDS_OPT_DEVIDE_PRINT_TOFITPAPER", "按纸张分割打印");
	extfun.setResLang("IDS_TOGETHER_PRINT", "多页");
	extfun.setResLang("IDS_OPT_PAGECOUNT_TOPRINT", "每面打印页数");
	extfun.setResLang("IDS_OPT_PRINT_ORDER", "页面顺序");
	extfun.setResLang("IDS_OPT_HORIZON", "水平");
	extfun.setResLang("IDS_OPT_VERTICAL", "垂直");
	extfun.setResLang("IDS_OPT_PRINT_DIRECTION", "打印方向");
	extfun.setResLang("IDS_OPT_PORTRAIT", "垂直");
	extfun.setResLang("IDS_OPT_LANDSCAPE", "水平");
	extfun.setResLang("IDS_OPT_OPTION", "选项");
	extfun.setResLang("IDS_OPT_CONFIRM", "确定");
	extfun.setResLang("IDS_OPT_CANCEL", "取消");
	extfun.setResLang("IDS_OPT_CLOSE", "Close");
	extfun.setResLang("IDS_OPT_SAVE", "저장");
	extfun.setResLang("IDS_OPT_OZD_SAVE_OPTION", "保存选项");
	extfun.setResLang("IDS_OPT_PASSWORD", "密码");
	extfun.setResLang("IDS_OPT_MEMOADD_OK", "包含编辑内容");
	extfun.setResLang("IDS_OPT_SAVE_ALLREPORT", "保存所有报表");
	extfun.setResLang("IDS_OPT_INCLUDE_IMG", "包含图片");
	extfun.setResLang("IDS_OPT_FILE_TYPE", "文件类型");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE", "Excel 保存选项");
	extfun.setResLang("IDS_OPT_WORD_SAVE", "Word 保存选项");
	extfun.setResLang("IDS_OPT_DOCX_SAVE", "Word 保存选项");
	extfun.setResLang("IDS_OPT_PPT_SAVE", "PowerPoint 保存选项");
	extfun.setResLang("IDS_OPT_HTML_SAVE", "HTML 保存选项");
	extfun.setResLang("IDS_OPT_CSV_SAVE", "CSV 保存选项");
	extfun.setResLang("IDS_OPT_TEXT_SAVE", "TEXT 保存选项");
	extfun.setResLang("IDS_OPT_JPG_SAVE", "JPG 保存选项");
	extfun.setResLang("IDS_OPT_TIFF_SAVE", "TIFF 保存选项");
	extfun.setResLang("IDS_OPT_HWP_SAVE", "Hangul Option");
	extfun.setResLang("IDS_OPT_HWP97_SAVE", "Hangul97 Option");
	extfun.setResLang("IDS_OPT_MHT_SAVE", "MHT 保存选项");
	extfun.setResLang("IDS_OPT_SAVE_FORM", "分隔标记");
	extfun.setResLang("IDS_OPT_PAGE", "页面");
	extfun.setResLang("IDS_OPT_FONT", "字体");
	extfun.setResLang("IDS_OPT_FORMAT", "格式");
	extfun.setResLang("IDS_OPT_AUTO_FIT", "自动调整");
	extfun.setResLang("IDS_OPT_CELL_MINIMUM_SIZE_CELL", "单元格最小值");
	extfun.setResLang("IDS_OPT_SAVE_MODE", "保存类型");
	extfun.setResLang("IDS_OPT_KEEP_FORM_ATTR", "保持报表原样，属性");
	extfun.setResLang("IDS_OPT_IGNORE_COLOR_OUTLINE_CELL", "不含颜色，边框，单元格合并");
	extfun.setResLang("IDS_OPT_REMOVE_CELL_AFTERDIVIDE", "拆分后删除周边单元格");
	extfun.setResLang("IDS_OPT_SAVE_SHEET_PER_COLPAGE", "一列的页保存为一个工作表");
	extfun.setResLang("IDS_OPT_SAVE_SHEET_PAGE", "一页保存为一个工作表");
	extfun.setResLang("IDS_OPT_COLUMN_FIRST", "先行后列");
	extfun.setResLang("IDS_OPT_ROW_FIRST", "先列后行");
	extfun.setResLang("IDS_OPT_REMOVE_PAGE_GAP", "除去页间空白");
	extfun.setResLang("IDS_OPT_SIZE_COLON", "字号:");
	extfun.setResLang("IDS_OPT_REMOVE_LINE", "删除行");
	extfun.setResLang("IDS_OPT_EXCLUDE_FIRST_PAGE", "第一页除外");
	extfun.setResLang("IDS_OPT_ONLY_FIRST_PAGE", "只选第一页");
	extfun.setResLang("IDS_OPT_ALL_PAGE", "所有页");
	extfun.setResLang("IDS_OPT_LINE_SCOPE_LINE_NUMBER", "请键入行号和/或用逗号(, )\n分隔的行范围。例如）1-3，5，12");
	extfun.setResLang("IDS_OPT_CHANGE_TXT_TO_INTEGER", "把文本型数字转换为数字");
	extfun.setResLang("IDS_OPT_APPLY_ONLYLABEL_NUMBER", "只适用数值型标签");
	extfun.setResLang("IDC_CHECK_APPLY_DATETIMEFORMAT", "Date type text convert to date");
	extfun.setResLang("IDS_OPT_CHANGE_AS_NORMAL", "转换为常规(单元格格式)");
	extfun.setResLang("IDS_OPT_FONT_COLON", "字体:");
	extfun.setResLang("IDS_OPT_WIDTH", "宽度");
	extfun.setResLang("IDS_OPT_HEIGHT", "高度");
	extfun.setResLang("IDS_OPT_SAVE_MHT_TYPE", "以mht格式保存 （支持office XP或更高版本）");
	extfun.setResLang("IDS_OPT_TABLE_SAVE_WAY", "表");
	extfun.setResLang("IDS_OPT_TABLE_TYPE_WAY", "保存为表格           ");
	extfun.setResLang("IDS_OPT_BAND_SAVE_WAY", "Band");
	extfun.setResLang("IDS_OPT_BAND_SAVE_PAGE", "将页眉/页脚Band保存在页眉/页脚");
	extfun.setResLang("IDS_OPT_PPT_SAVE_WAY", "保存类型");
	extfun.setResLang("IDS_OPT_MHTD_SAVE_PAGE", "保存为 mht 格式(支持 office XP 以上)");
	extfun.setResLang("IDS_OPT_FONT_SIZE_SETTING", "设置字号");
	extfun.setResLang("IDS_OPT_PAGE_BETWEEN", "页间间隔");
	extfun.setResLang("IDS_OPT_PER_PAGE_SAVE", "分页保存");
	extfun.setResLang("IDS_OPT_LINE_COUNT_COLON", "行数 :");
	extfun.setResLang("IDS_OPT_OFFSET_COLON", "偏移量 :");
	extfun.setResLang("IDS_OPT_STARTPOINT_HTMLDOC", "文档开始位置");
	extfun.setResLang("IDS_OPT_ENCODING_COLON", "编码 :");
	extfun.setResLang("IDS_OPT_X_AXIS", "X轴");
	extfun.setResLang("IDS_OPT_Y_AXIS", "Y轴");
	extfun.setResLang("IDS_OPT_OFFSET", "偏移");
	extfun.setResLang("IDS_OPT_SEPARATION", "分隔符");
	extfun.setResLang("IDS_OPT_SEPARATOR", "分隔符");
	extfun.setResLang("IDS_OPT_USER_DEFINE", "自定义");
	extfun.setResLang("IDS_OPT_SEPARATION_TYPE", "分页符");
	extfun.setResLang("IDS_OPT_PAGE_BRACKET", "<PAGE>");
	extfun.setResLang("IDS_OPT_SET_PAGELINE", "空白行数");
	extfun.setResLang("IDS_OPT_CHAR_NUMBER", "数字");
	extfun.setResLang("IDS_OPT_ADD_SEPARATOR", "添加千位分隔符");
	extfun.setResLang("IDS_OPT_REMOVE_SEPARATOR", "取消千位分隔符");
	extfun.setResLang("IDS_OPT_PAGE_SEPARATION", "分页符");
	extfun.setResLang("IDS_OPT_LABEL_SAVE", "标签保存方式");
	extfun.setResLang("IDS_OPT_LABEL_SIZE", "固定标签尺寸");
	extfun.setResLang("IDS_OPT_POSITION_SAVE", "位置保存方式");
	extfun.setResLang("IDS_OPT_VERTREL_TOPARA", "将纵向设置为文段");
	extfun.setResLang("IDS_OPT_BACKGROUND_BAND", "Save background band to background page");
	extfun.setResLang("IDS_OPT_TITLE_COLON", "标题  :");
	extfun.setResLang("IDS_OPT_DISPLAY_OPTION", "显示选项");
	extfun.setResLang("IDS_OPT_GRIDLINES", "显示网格线");
	extfun.setResLang("IDS_OPT_ENCODING_WAY", "编码方式");
	extfun.setResLang("IDS_OPT_ENCODING_G3", "G3");
	extfun.setResLang("IDS_OPT_ENCODING_G4", "G4");
	extfun.setResLang("IDS_OPT_ENCODING_SAVEAS_ONEFILE", "单文档保存");
	extfun.setResLang("IDS_OPT_RATIO", "比例");
	extfun.setResLang("IDS_OPT_ZOOM_INOUT", "缩放比例");
	extfun.setResLang("IDS_OPT_SET_DPI", "根据分辨率调整大小");
	extfun.setResLang("IDS_OPT_DPI", "分辨率");
	extfun.setResLang("IDS_OPT_SIZE", "字号");
	extfun.setResLang("IDS_OPT_SAVE_RATIO", "缩放保存");
	extfun.setResLang("IDS_OPT_COMPRESSION", "压缩");
	extfun.setResLang("IDS_OPT_QUALITY", "质量");
	extfun.setResLang("IDS_OPT_USE_INDENT", "使用缩进功能");
	extfun.setResLang("IDS_OPT_DATA_SAVE", "数据保存");
	extfun.setResLang("IDS_OPT_FIND_WHAT", "查找内容:");
	extfun.setResLang("IDS_OPT_MATCH_WHOLE_WORD", "全字匹配");
	extfun.setResLang("IDS_OPT_MATCH_CASE", "区分大小写");
	extfun.setResLang("IDS_OPT_DIRECTION", "方向");
	extfun.setResLang("IDS_OPT_SEARCH_UP", "向上");
	extfun.setResLang("IDS_OPT_SEARCH_DOWN", "向下");
	extfun.setResLang("IDS_OPT_NEXT", "查找下一处");
	extfun.setResLang("IDS_OPT_REFRESH_REPORT", "刷新");
	extfun.setResLang("IDS_OPT_INTERVAL", "周期");
	extfun.setResLang("IDS_OPT_HH", "时");
	extfun.setResLang("IDS_OPT_MM", "分");
	extfun.setResLang("IDS_OPT_SS", "秒");
	extfun.setResLang("IDS_OPT_REFRESH_NOW", "刷新");
	extfun.setResLang("IDS_OPT_START", "开始");
	extfun.setResLang("IDS_OPT_STOP", "停止");
	extfun.setResLang("IDS_OPT_LEFT_COLON", "左:");
	extfun.setResLang("IDS_OPT_RIGHT_COLON", "右:");
	extfun.setResLang("IDS_OPT_TOP_COLON", "上:");
	extfun.setResLang("IDS_OPT_BOTTOM_COLON", "下:");
	extfun.setResLang("IDS_OPT_PAGE_SETUP", "页面设置");
	extfun.setResLang("IDS_OPT_MARGIN", "页边距");
	extfun.setResLang("IDS_OPT_UNIT", "度量单位");
	extfun.setResLang("IDS_OPT_UNIT_COLON", "单位 :");
	extfun.setResLang("IDS_OPT_MARGIN_OPTION", "页边距选项");
	extfun.setResLang("IDS_OPT_MARGIN_DEFAULT", "默认页边距");
	extfun.setResLang("IDS_OPT_MARGIN_AUTO_ADJUST", "自动调整");
	extfun.setResLang("IDS_OPT_HTML_VERSION", "版本");
	extfun.setResLang("IDS_OPT_HTML_VERSION_COLON", "HTML 版本 :");
	extfun.setResLang("IDS_OPT_TOTAL", "全部");
	extfun.setResLang("IDS_OPT_REPORT_STRUCTURE", "查看报表结构");
	extfun.setResLang("IDS_OPT_LABEL_FORMAT", "标签格式");
	extfun.setResLang("IDS_OPT_PARAGRAPH", "段落");
	extfun.setResLang("IDS_OPT_FILL", "填充");
	extfun.setResLang("IDS_OPT_LINECOLOR", "边框");
	extfun.setResLang("IDS_OPT_ETC", "其它");
	extfun.setResLang("IDS_OPT_ALIGNMENT", "文本对齐方式");
	extfun.setResLang("IDS_OPT_TXT_DIRECTION", "文字方向");
	extfun.setResLang("IDS_OPT_INTERNAL_MARGIN", "边距");
	extfun.setResLang("IDS_OPT_PREVIEW", "预览");
	extfun.setResLang("IDS_OPT_HORIZON_COLON", "水平 :");
	extfun.setResLang("IDS_OPT_VERTICAL_COLON", "垂直 :");
	extfun.setResLang("IDS_OPT_LINE_SPACE_COLON", "行距 :");
	extfun.setResLang("IDS_OPT_INDENT_COLON", "缩进 :");
	extfun.setResLang("ID_OPT_PARAMETERS_TITLE_LABEL", "更改参数值");
	extfun.setResLang("IDS_OPT_EXIT", "结束");
	extfun.setResLang("IDS_OPT_OZZPASSWORD", "密码");
	extfun.setResLang("IDS_OPT_OZZPASSWORD_CHECK", "确认密码");
	extfun.setResLang("IDS_OPT_ID", "用户名");
	extfun.setResLang("IDS_OPT_SECURITY", "安全");
	extfun.setResLang("IDS_OPT_PRODUCT_INFO", "产品信息");
	extfun.setResLang("IDS_OPT_OZ_INFO", "产品 信息");
	extfun.setResLang("IDS_OPT_ERROR_CODE_COLON", "错误代码:");
	extfun.setResLang("IDS_OPT_GENERAL_MSG_COLON", "信息:");
	extfun.setResLang("IDS_OPT_VIEW_DETAIL", "详细");
	extfun.setResLang("IDS_OPT_DETAIL_MSG_COLON", "详细信息:");
	extfun.setResLang("IDS_OPT_TEXT_CONTROL", "文本控制");
	extfun.setResLang("IDS_OPT_SHRINK_TO_FIT", "缩小字体填充");
	extfun.setResLang("IDS_OPT_PASSWORD2", "确定");
	extfun.setResLang("IDS_OPT_DM_BARCODE", "DataMatrix 码");
	extfun.setResLang("IDS_OPT_FONT_STYLE_COLON", "字形:");
	extfun.setResLang("IDS_OPT_COLOR_COLON", "颜色:");
	extfun.setResLang("IDS_OPT_INTERVAL_COLON", "字距:");
	extfun.setResLang("IDS_OPT_STRETCH_COLON", "Stretch :");
	extfun.setResLang("IDS_OPT_EFFECT", "效果");
	extfun.setResLang("IDS_OPT_UNDERLINE", "下划线");
	extfun.setResLang("IDS_OPT_STRIKEOUT", "删除线");
	extfun.setResLang("IDS_OPT_DOUBLE_STRIKEOUT", "双删除线");
	extfun.setResLang("IDS_OPT_NO_FILL", "无填充");
	extfun.setResLang("IDS_OPT_TRANSPARENCY", "透明度:");
	extfun.setResLang("IDS_OPT_GRADIENT", "渐变");
	extfun.setResLang("IDS_OPT_USE_GRADIENT", "渐变填充");
	extfun.setResLang("IDS_OPT_SLASH", "斜上");
	extfun.setResLang("IDS_OPT_BACK_SLASH", "斜下");
	extfun.setResLang("IDS_OPT_START_POSITION", "起点");
	extfun.setResLang("IDS_OPT_FROM_EDGE", "角部");
	extfun.setResLang("IDS_OPT_DIRECT", "正向");
	extfun.setResLang("IDS_OPT_FROM_CENTER", "中心");
	extfun.setResLang("IDS_OPT_REVERSE", "反向");
	extfun.setResLang("IDS_OPT_THICKNESS_W", "粗细(W):");
	extfun.setResLang("IDS_OPT_STYLE_Y", "线型(Y):");
	extfun.setResLang("IDS_OPT_COLOR_C", "颜色(C):");
	extfun.setResLang("IDS_OPT_CLIPPING", "裁剪");
	extfun.setResLang("IDS_OPT_WORD_WRAP", "自动换行");
	extfun.setResLang("IDS_OPT_WORD_WRAP_TYPE", "自动换行方式");
	extfun.setResLang("IDS_OPT_IGNORE_SPACE", "忽略空格");
	extfun.setResLang("IDS_OPT_NON_ASCII_WORD", "防止切断单词");
	extfun.setResLang("IDS_OPT_TOOLTIP_TEXT", "工具提示...");
	extfun.setResLang("IDS_OPT_BASIC", "Basic");
	extfun.setResLang("IDS_OPT_OUTLINE", "Outline");
	extfun.setResLang("IDS_OPT_3D", "3D");
	extfun.setResLang("IDS_OPT_ENGRAVE", "Engrave");
	extfun.setResLang("IDS_OPT_SEGMENT", "Segments");
	extfun.setResLang("IDS_OPT_HOLLOW", "Hollow");
	extfun.setResLang("IDS_OPT_SHADOW", "Shadow");
	extfun.setResLang("IDS_OPT_IMAGE_STYLE", "样式 :");
	extfun.setResLang("IDS_OPT_BARCODE_STYLE", "类型:");
	extfun.setResLang("IDS_OPT_DATA_GAP", "数据间距:");
	extfun.setResLang("IDS_OPT_DATA_POSITION", "数据位置:");
	extfun.setResLang("IDS_OPT_BARCODE_MARGIN", "边距:");
	extfun.setResLang("IDS_OPT_ALIGN_HORIZONTALLY", "水平对齐:");
	extfun.setResLang("IDS_OPT_RATION_COLON", "比例:");
	extfun.setResLang("IDS_OPT_PRINTING_SCALE", "打印比例:");
	extfun.setResLang("IDS_OPT_ROTATION_COLON", "旋转:");
	extfun.setResLang("IDS_OPT_TITLE_GAP", "标题间距:");
	extfun.setResLang("IDS_OPT_TITLE_POSITION", "标题位置:");
	extfun.setResLang("IDS_OPT_BARCODE_ERROR_OPTION", "显示错误:");
	extfun.setResLang("IDS_OPT_DISPLAY_ERROR_DATA", "数据错误");
	extfun.setResLang("IDS_OPT_DISPLAY_ERROR_SIZE", "尺寸错误");
	extfun.setResLang("IDS_OPT_DISPLAY_EMPTY_DATA", "空数据");
	extfun.setResLang("IDS_OPT_PDF_IMAGE_STYLE", "图像样式:");
	extfun.setResLang("IDS_OPT_PDF_ROW_NUMBER", "行数:");
	extfun.setResLang("IDS_OPT_PDF_COL_NUMBER", "列数:");
	extfun.setResLang("IDS_OPT_PDF_ECC", "纠错等级:");
	extfun.setResLang("IDS_OPT_PDF_X_SCALE", "X 大小:");
	extfun.setResLang("IDS_OPT_PDF_Y_SCALE", "Y 大小:");
	extfun.setResLang("IDS_OPT_BORDER_COLOR", "边框颜色 :");
	extfun.setResLang("IDS_OPT_BORDER_TRANSPARENCY", "Border Transparency :");
	extfun.setResLang("IDS_OPT_FILL_COLOR", "填充颜色 :");
	extfun.setResLang("IDS_OPT_THICKNESS", "粗细 :");
	extfun.setResLang("IDS_OPT_SHAPE_NO_FILL", "透明 :");
	extfun.setResLang("IDS_OPT_LINE_TYPE", "类型 :");
	extfun.setResLang("IDS_OPT_TOOLTIP_TEXT_COLON", "工具提示 :");
	extfun.setResLang("IDS_OPT_EDIT_CHART", "编辑图表");
	extfun.setResLang("IDS_OPT_SHOW_DATA", "显示数据标签");
	extfun.setResLang("IDS_OPT_EDIT_SHAPE", "编辑形状");
	extfun.setResLang("IDS_FORCS_RV", "Forcs(R) OZ Report Viewer");
	extfun.setResLang("IDS_OPT_EXCEL_LINE", "线条");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE_TYPE", "保存形式");
	extfun.setResLang("IDS_OPT_JPG_ZOOM_INOUT", "缩放比例");
	extfun.setResLang("IDS_OPT_ZOOM_INOUT_COLON", "缩放比例: ");
	extfun.setResLang("IDS_OPT_QUALITY_COLON", "质量: ");
	extfun.setResLang("IDS_OPT_TIFF_SIZE", "自定义大小");
	extfun.setResLang("IDS_OPT_PAGELINE", "Line");
	extfun.setResLang("IDS_OPT_WORD_BAND_SAVE_PAGE", "将 Page Header/Footer Band 保存到页眉/页脚");
	extfun.setResLang("IDS_OPT_PRINT_MULTIDOC", "多文档");
	extfun.setResLang("ID_PAGE_CONTROL_WINDOW", "页面导航");
	extfun.setResLang("IDS_OPT_FONT_NAME_COLON", "字体:");
	extfun.setResLang("IDS_OPT_FONT_OPTION", "选项");
	extfun.setResLang("IDS_OPT_AUTO_SELECTED", "自动调整");
	extfun.setResLang("IDS_OPT_SIDE", "宽度");
	extfun.setResLang("IDS_OPT_LENGTH", "高度");
	extfun.setResLang("IDS_OPT_OTHER", "自定义");
	extfun.setResLang("IDS_OPT_FONT_SAVE_WAY", "字体");
	extfun.setResLang("IDS_OPT_HORIZONTAL_NAVI", "水平");
	extfun.setResLang("IDS_OPT_VERTICAL_NAVI", "垂直");
	extfun.setResLang("IDS_OPT_PNG_SAVE", "PNG 保存选项");
	extfun.setResLang("IDS_OPT_GIF_SAVE", "GIF 保存选项");
	extfun.setResLang("IDS_OPT_REMOVE_LINES", "删除行");
	extfun.setResLang("IDS_OPT_ENCODING_HDM", "编码 : ");
	extfun.setResLang("IDS_OPT_SVG_SAVE", "SVG 保存选项");
	extfun.setResLang("IDS_OPT_PDF_CHANGEABLE", "允许更改");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE1", "无");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE2", "注释, 填写表单和签名现有签名域");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE3", "页面布局, 填写表单和签名现有签名域");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE4", "除了提取页面");
	extfun.setResLang("IDS_OPT_SAVE_WAY_BASE", "保存方式");
	extfun.setResLang("IDS_OPT_SAVE_LARGEBUNDLE_BYPAGE", "单页/分页绑定报表");
	extfun.setResLang("IDS_OPT_SAVE_LARGE_BUNDLE", "单页保存");
	extfun.setResLang("IDS_OPT_SAVE_BY_PAGE", "分页保存");
	extfun.setResLang("IDS_OPT_KEEP_SAVING", "keep saving");
	extfun.setResLang("IDC_TITLE_SECURITY", "限制打开");
	extfun.setResLang("IDC_EDIT_PASSWORD", "密码");
	extfun.setResLang("IDC_EDIT_PASSWORD_VERIFY", "确认密码");
	extfun.setResLang("IDC_ZIP_GROUP", "压缩");
	extfun.setResLang("IDC_COMPRESS_ON_SAVE", "压缩保存");
	extfun.setResLang("IDC_PAPER_SETUP", "纸张设置");
	extfun.setResLang("IDC_CHECK_ADJUST", "按纸张大小缩放");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE_DETAIL", "请键入页码和/或用逗号分隔的页码范围。");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE_DETAIL2", "(例如:1.3.5-12)");
	extfun.setResLang("IDS_OPT_NEXCEL_SAVE", "Nexcel 保存选项");
	extfun.setResLang("IDS_OPT_NEXCEL_SAVE2", "Nexcel 保存选项(高级)");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE2", "Excel 保存选项(高级)");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM", "比例");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM_RATIO", "缩放比例: ");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM_RATIO2", "缩放比例(%)");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES", "凍結窗格");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_ROW", "行: ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_COL", "列: ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_ROW_M", "行 ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_COL_M", "列 ");
	extfun.setResLang("IDC_EDIT_ZIP_PASSWORD", "打开口令");
	extfun.setResLang("IDC_EDIT_ZIP_PASSWORD_VERIFY", "确认打开口令");
	extfun.setResLang("IDS_OPT_BMP_SAVE", "BMP 保存选项");
	extfun.setResLang("IDS_OPT_RTF_SAVE", "RTF 保存选项");
	extfun.setResLang("IDS_OPT_SELECTREPORT", "指定报表:");
	extfun.setResLang("IDS_OPT_SELECTREPORT2", "选择报表...");
	extfun.setResLang("IDS_OPT_SELECTREPORT_TITLE", "选择报表");
	extfun.setResLang("IDS_OPT_CHECK_SELECT_ALL", "全部选择");
	extfun.setResLang("ID_PAGE_CONTROL_NAVIGATOR", "页面导航");
	extfun.setResLang("ID_PARAMETER_TOOLBAR", "Parameter toolbar");
	extfun.setResLang("IDS_OPT_ENCODING_JPG", "JPG");
	extfun.setResLang("IDS_OPT_MARGIN_COLON", "边距 :");
	extfun.setResLang("IDS_OPT_SEARCH", "查找");
	extfun.setResLang("IDS_CONSOLE", "Console");
	extfun.setResLang("IDS_LICENSE_ERROR_TITLE", "Failed to verify licensing.");
	extfun.setResLang("IDS_LICENSE_ERROR_EXPIRED", "The license has been expired.");
	extfun.setResLang("IDS_LICENSE_ERROR_VERSION", "The license does not match with software version.");
	extfun.setResLang("IDS_LICENSE_ERROR_CERT", "Failed to verify the certificate.");
	extfun.setResLang("IDS_LICENSE_ERROR_FILENOTFOUND", "Cannot find license file.");
	extfun.setResLang("IDS_LICENSE_ERROR_DOMAIN", "The license does not match with domain.");
	extfun.setResLang("IDS_OPT_CELL_SAVE", "Cell 保存选项");
	extfun.setResLang("IDS_OPT_CELL_SAVE2", "Cell 保存选项(高级)");
	extfun.setResLang("IDS_SELECT_FILE", "文件");
	extfun.setResLang("IDS_SHOOT", "相机");
	extfun.setResLang("IDS_SHOOT_OR_SELECT_FILE", "Shoot or Select File");
	extfun.setResLang("IDS_IMAGE_MERGE_ITEM", "Combine photos");
	extfun.setResLang("IDS_IMAGE_EDIT_TITLE", "照片编辑");
	extfun.setResLang("IDS_IMAGE", "照片");
	extfun.setResLang("IDS_IMAGE_EDIT_DONE", "完成");
	extfun.setResLang("IDS_IMAGE_EDIT_CANCEL", "取消");
	extfun.setResLang("IDS_IMAGE_EDIT_ROTATE", "旋转");
	extfun.setResLang("IDS_IMAGE_EDIT_FILL", "填充");
	extfun.setResLang("IDS_IMAGE_EDIT_FIT", "适应");
	extfun.setResLang("IDS_DLG_EDIT", "编辑");
	extfun.setResLang("IDS_THUMBNAIL_ALLOWCLOSE", "关闭");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_LEFT", "文本左对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_CENTER", "居中");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_RIGHT", "文本右对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_HDIST", "水平分散对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_HJUSTIFY", "水平两端对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_TOP", "顶端对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_MIDDLE", "垂直居中");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_BOTTOM", "底端对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_VDIST", "垂直分散对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_VJUSTIFY", "垂直两端对齐");
	extfun.setResLang("IDS_LAYOUT_MOVE_LEFT", "Text direction left");
	extfun.setResLang("IDS_LAYOUT_MOVE_TOP", "Text direction top");
	extfun.setResLang("IDS_LAYOUT_MOVE_RIGHT", "Text direction right");
	extfun.setResLang("IDS_LAYOUT_MOVE_BOTTOM", "Text direction bottom");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_HORIZONTAL", "HORIZONTAL");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_VERTICAL", "VERTICAL");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_CLOCKWISE", "CLOCKWISE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_COUNTERCLOCKWISE", "COUNTERCLOCKWISE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_VERTICAL_2BYTE", "VERTICAL_2BYTE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_HORIZONTAL_2BYTE", "HORIZONTAL_2BYTE");
	extfun.setResLang("IDS_BORDER_TOP", "上框线");
	extfun.setResLang("IDS_BORDER_MIDDLE", "内部横框线");
	extfun.setResLang("IDS_BORDER_BOTTOM", "下框线");
	extfun.setResLang("IDS_BORDER_LEFT", "左框线");
	extfun.setResLang("IDS_BORDER_CENTER", "内部竖框线");
	extfun.setResLang("IDS_BORDER_EMPTY", "无框线");
	extfun.setResLang("IDS_BORDER_RIGHT", "右框线");
	extfun.setResLang("IDS_BORDER_ALL", "所有框线");
	extfun.setResLang("IDS_BORDER_OUTSIDE", "外侧框线");
	extfun.setResLang("IDS_BORDER_INSIDE", "内部框线");
	extfun.setResLang("IDS_BORDER_USER", "自定义");
	extfun.setResLang("ID_TITLEBAR_THUMBNAIL_TITLE", "缩略图");
	extfun.setResLang("ID_TITLEBAR_TREE_TITLE", "报表树");
	extfun.setResLang("IDS_SEAL_DESCRIPTION", "Please align the seal recognition area with the green guidelines.");
	extfun.setResLang("IDS_DIALOG_FORMAT", "格式");
	extfun.setResLang("IDS_SIGNEX_SIGN", "서명 입력");
	extfun.setResLang("IDS_SIGNEX_SEAL", "인감 스캔");
	extfun.setResLang("IDS_ATTACHMENTS_FILE_SIZE_LIMIT", "文件大小限制：每个文件 %s");
	extfun.setResLang("IDS_ATTACHMENTS_SUMMARY_TITLE", "文件列表");
	extfun.setResLang("IDS_ATTACHMENTS_COUNT", "附件数量");
	extfun.setResLang("IDS_ATTACHMENTS_SELECT", "选择文件");
	extfun.setResLang("IDS_ATTACHMENTS_APPEND", "添加文件");
	extfun.setResLang("IDS_ATTACHMENTS_DOWNLOAD", "下载");
	extfun.setResLang("IDS_ATTACHMENTS_DELETE", "删除");
	extfun.setResLang("IDS_ATTACHMENTS_EMPTY", "Drag and drop a file here\nOR\nClick \"Add\" button.");
	extfun.setResLang("IDS_ATTACHMENTS_MAXSIZE", "Max size is n MB");
	extfun.setResLang("IDS_ATTACHMENTS_IMAGE_INDIVIDUALLY", "Attach individually");
	extfun.setResLang("IDS_ATTACHERROR_UNSUPPORTED", "Unsupported file format");
	extfun.setResLang("IDS_ATTACHERROR_OVERSIZE", "Max size exceeded");
	extfun.setResLang("IDS_ATTACHERROR_INVALID_PDF", "Unknown PDF file");
	extfun.setResLang("IDS_ATTACHERROR_PASSWORD_PDF", "Password protected PDF file");
	extfun.setResLang("IDS_SEAL_IMAGE_UPLOAD", "도장 이미지 업로드");
	extfun.setResLang("IDS_SEAL_IMAGE_REUPLOAD", "도장 이미지 다시 업로드");
	extfun.setResLang("IDS_SEAL_IMAGE_APPLY", "적용하기");
	extfun.setResLang("IDS_SCAN_SUCCESS", "도장 이미지 인식에 성공하였습니다. ");
	extfun.setResLang("IDS_SCAN_FAIL", "도장 이미지를 인식할 수 없습니다. ");
	extfun.setResLang("IDS_SCAN_RETRY", "다시 인식하시려면 다시 스캔 해주세요.");
	extfun.setResLang("IDS_SCAN_REUPLOAD", "다시 선택하시려면 이미지를 다시 업로드 해주세요.");
	extfun.setResLang("IDS_SCAN_RETRY_LINK", "다시 스캔");
	extfun.setResLang("IDS_SCAN_REUPLOAD_LINK", "다시 업로드");
	extfun.setResLang("IDS_SCAN_UPLOAD_FAIL", "이미지를 다시 업로드 해주세요.");
	extfun.setResLang("IDS_MSG_SCAN_WAITING", "이미지를 분석 중입니다. 잠시만 기다려주세요.");
	extfun.setResLang("IDS_OPT_FONT_STYLE", "字形");
	extfun.setResLang("IDS_OPT_COLOR", "颜色");
	extfun.setResLang("IDS_REMOVE_MEMO", "是否删除?");
	extfun.setResLang("IDS_OPT_MEMO", "Memo");
	extfun.setResLang("IDS_OZVS_ERROR_PLAY", "无法执行视频签名。");
	extfun.setResLang("IDS_OZVR_RECORD_COMPLETED", "Recording has been completed.");
	extfun.setResLang("IDS_OZVR_ERROR_PLAY", "播放失败。");
}