with (__oznamespace__) {
	extfun.setResLang("IDS_GANTT_YEAR", "年");
	extfun.setResLang("IDS_GANTT_QUARTER", "季度");
	extfun.setResLang("IDS_GANTT_MONTH", "月");
	extfun.setResLang("IDS_GANTT_DAY", "日");
	extfun.setResLang("IDS_BMT_START_DATA", "資料查詢開始時間:");
	extfun.setResLang("IDS_BMT_END_DATA", "資料查詢完成時間:");
	extfun.setResLang("IDS_BMT_START_BIND", "綁定開始時間:");
	extfun.setResLang("IDS_BMT_END_BIND", "綁定完成時間:");
	extfun.setResLang("IDS_BMT_START_LOAD", "範本生成開始時間:");
	extfun.setResLang("IDS_BMT_END_LOAD", "範本生成完成時間:");
	extfun.setResLang("IDS_BMT_START_EXPORT", "輸出開始時間:");
	extfun.setResLang("IDS_BMT_END_EXPORT", "輸出完成時間:");
	extfun.setResLang("IDS_MSG_ABOUT_FORCS", "\n注意: 該電腦程式受著作權法和國際協約的保護。\n\n非法複製及發佈全部或部分 程式的行為，\n將受到民事及 刑事法的嚴厲追究，並成為起訴原由。");
	extfun.setResLang("IDS_MSG_LOADER_CREATE_TEMPLATE", "正在生成報表範本。");
	extfun.setResLang("IDS_MSG_LOADER_PREPARE_CONNECTION", "正在準備連接伺服器。");
	extfun.setResLang("IDS_MSG_LOADER_CONNECTED", "成功連接伺服器。");
	extfun.setResLang("IDS_MSG_LOADER_READ_REPORT_BYTE_FROM_REMOTE", "正在從伺服器讀取報表Form。");
	extfun.setResLang("IDS_MSG_LOADER_READ_DATA_FROM_REMOTE", "正在從伺服器讀取資料。");
	extfun.setResLang("IDS_MSG_LOADER_LAUNCH_MODE", "報表範本生成信息");
	extfun.setResLang("IDS_MSG_LOADER_GENERATE_REPORT", "正在生成報表。");
	extfun.setResLang("IDS_MSG_MAIN_READY", "準備");
	extfun.setResLang("IDS_MSG_OZZ_OPEN", "正在打開OZD文件。");
	extfun.setResLang("IDS_MSG_MAIN_BINDING", "正在生成報表。");
	extfun.setResLang("IDS_MSG_MAIN_MSG", "信息");
	extfun.setResLang("IDS_ERR_LOADER_CANNOT_DECRYPT", "安全控制項不符，無法打開檔。");
	extfun.setResLang("IDS_ERR_TITLE_PARAMETER", "參數");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_RGB", "該參數值為錯誤的RGB值。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_ZOOM", "用於參數的縮放值有錯。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_CHILDCOUNT", "輸入的下級報表數量設置出錯。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_REFRESH", "報表刷新週期輸入值無效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_RANGE", "PDF保存範圍無效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_COPIES", "列印份數出錯。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_PAGESINONE", "多頁列印的每頁列印的張數無效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_SPOOL_PAGES", "印表機Spool列印值無效。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEWIDTH", "設置了錯誤的Window橫向寬度。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEHEIGHT", "設置了錯誤的Window縱向高度。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEX", "設置了錯誤的窗X座標。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEY", "設置了錯誤的窗Y座標。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_ICON_SIZE", "設置的圖示大小參數值無效。");
	extfun.setResLang("IDS_ERR_PARAM_NOT_INT", "參數值無法轉換為數值。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_LINES", "錯誤的頁面之間的行數。");
	extfun.setResLang("IDS_ERR_DLL_LOAD_FAILED", "JAR庫載入失敗。\n程式可能無法正常運行。");
	extfun.setResLang("IDS_ERR_LOADER_SERVER_NO_MSG", "資源庫不存在的信息代碼。");
	extfun.setResLang("IDS_ERROR_SEARCH_CAN_NOT_FIND", "無法找到。");
	extfun.setResLang("IDS_FORBIDDEN_CHRS", ",./?_");
	extfun.setResLang("IDS_TEXT_ENCODING_ANSI", "ANSI");
	extfun.setResLang("IDS_TEXT_ENCODING_UNICODE", "國際碼");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_BASELINE_DATETIME", "server_baseline_datetime 參數值使用格式錯誤。");
	extfun.setResLang("IDS_NOTIFICAION_MESSAGEBOX", "通知");
	extfun.setResLang("IDS_NOTIFICAION_NODATA", "沒有查詢的資料");
	extfun.setResLang("IDS_OKSTRING", "確認");
	extfun.setResLang("IDS_CANCELSTRING", "取消");
	extfun.setResLang("IDS_YESSTRING", "是");
	extfun.setResLang("IDS_NOSTRING", "否");
	extfun.setResLang("IDS_MSG_END_MAKETEMPLATE", "");
	extfun.setResLang("IDS_MSG_ENDCHECKCONOPT", "連接選項確認完成。");
	extfun.setResLang("IDS_MSG_MAKETEMPLATE", "開始接收報表Form。");
	extfun.setResLang("IDS_MSG_STARTRCVFORM", "開始接收報表形式。");
	extfun.setResLang("IDS_MSG_STARTRCVDATA", "開始接收資料模組。");
	extfun.setResLang("IDS_MSG_STARTBINDING", "開始綁定報表。");
	extfun.setResLang("IDS_MSG_ENDRCVFORM", "報表Form接收完成。");
	extfun.setResLang("IDS_MSG_ENDRCVDATA", "資料模組接收完成。");
	extfun.setResLang("IDS_MSG_STARTCHECKCONOPT", "開始連接選項確認。");
	extfun.setResLang("IDS_STATIC_PROGRESSBAR_OZ", "正在運行OZ Report Viewer。");
	extfun.setResLang("IDS_MSG_START_DIRECT", "正在准备无预览打印或输出。");
	extfun.setResLang("IDS_MSG_IMAGEEXPORT_ERR", "");
	extfun.setResLang("IDS_JAPAN_HALF1", "");
	extfun.setResLang("IDS_JAPAN_HALF2", "");
	extfun.setResLang("IDS_JAPAN_FULL1", "");
	extfun.setResLang("IDS_JAPAN_FULL2", "");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_QUALITY", "參數不正確，品質值錯誤。");
	extfun.setResLang("ID_PAGE_LEFTMOST", "跳至水平方向的第一頁");
	extfun.setResLang("ID_PAGE_LEFT", "跳至水平方向的前一頁");
	extfun.setResLang("ID_PAGE_RIGHT", "跳至水平方向的下一頁");
	extfun.setResLang("ID_PAGE_RIGHTMOST", "跳至水平方向的最後一頁");
	extfun.setResLang("ID_ZOOM_RESET", "還原");
	extfun.setResLang("ID_ZOOM_IN", "放大");
	extfun.setResLang("ID_ZOOM_OUT", "縮小");
	extfun.setResLang("ID_PAGE_CONTROL", "選頁窗");
	extfun.setResLang("ID_PAGE_TOP", "跳至垂直方向的第一頁");
	extfun.setResLang("ID_PAGE_UP", "跳至垂直方向的前一頁");
	extfun.setResLang("ID_PAGE_DOWN", "跳至垂直方向的下一頁");
	extfun.setResLang("ID_PAGE_BOTTOM", "跳至垂直方向的最後一頁");
	extfun.setResLang("ID_FILE_ETCSAVE", "保存");
	extfun.setResLang("ID_OPT_HCDATA", "資料保存");
	extfun.setResLang("ID_OPT_BRAILLE", "Save electronic braille");
	extfun.setResLang("ID_ZOOM_IN_OUT", "放大/縮小比例");
	extfun.setResLang("ID_OZZ_OPEN", "打開");
	extfun.setResLang("ID_FILE_CLOSE", "關閉當前打開的文檔。\n關閉");
	extfun.setResLang("ID_FILE_PRINT", "列印當前打開的檔。\n列印");
	extfun.setResLang("ID_APP_ABOUT", "產品 信息...");
	extfun.setResLang("ID_APP_EXIT", "結束程式");
	extfun.setResLang("ID_PAGE", "");
	extfun.setResLang("ID_PAGE_PREVIOUS", "跳至前一頁");
	extfun.setResLang("ID_REPORT_PRINT", "列印");
	extfun.setResLang("ID_VIEWER_HELP", "說明");
	extfun.setResLang("ID_VIEWER_EXIT", "結束");
	extfun.setResLang("ID_BANKBOOK_PRINT", "存摺印表機列印");
	extfun.setResLang("ID_ETC", "其他菜單");
	extfun.setResLang("ID_EXPORT_PDF", "PDF 保存");
	extfun.setResLang("ID_EXPORT_XLS", "XLS 保存");
	extfun.setResLang("ID_EXPORT_DOC", "DOC 保存");
	extfun.setResLang("ID_EXPORT_DOCX", "DOCX 保存");
	extfun.setResLang("ID_EXPORT_OZD", "OZD 保存");
	extfun.setResLang("ID_EXPORT_HTML", "HTML 保存");
	extfun.setResLang("ID_EXPORT_PPT", "PPT 保存");
	extfun.setResLang("ID_EXPORT_SVG", "SVG 保存");
	extfun.setResLang("ID_EXPORT_TXT", "TXT 保存");
	extfun.setResLang("ID_EXPORT_CSV", "CSV 保存");
	extfun.setResLang("ID_EXPORT_TIF", "TIF 保存");
	extfun.setResLang("ID_EXPORT_JPG", "JPG 保存");
	extfun.setResLang("ID_EXPORT_HML", "HML 保存");
	extfun.setResLang("ID_EXPORT_HML97", "HML97 保存");
	extfun.setResLang("ID_EXPORT_HWPX", "HWPX 保存");
	extfun.setResLang("ID_EXPORT_ODT", "ODT 保存");
	extfun.setResLang("ID_EXPORT_MAIL", "MAIL 傳送");
	extfun.setResLang("ID_SEARCH_PARAM", "查詢");
	extfun.setResLang("ID_EXPORT_MHT", "MHT 保存");
	extfun.setResLang("ID_EXPORT_PNG", "PNG 保存");
	extfun.setResLang("ID_EXPORT_GIF", "GIF 保存");
	extfun.setResLang("ID_ZOOM_SINGLEPAGE_FITTOFRAME", "按適合畫面單頁");
	extfun.setResLang("ID_ZOOM_SINGLEPAGECONTINUOUS_FITTOWIDTH", "按適合寬度單頁連續");
	extfun.setResLang("ID_EXPORT_NXL", "NXL 保存");
	extfun.setResLang("ID_EXPORT_CELL", "CELL 保存");
	extfun.setResLang("ID_OPT_REFRESH", "報表刷新");
	extfun.setResLang("ID_OPT_LABEL", "添加Memo");
	extfun.setResLang("ID_OPT_IMAGE", "Add image");
	extfun.setResLang("ID_OPT_LINE", "插入線條");
	extfun.setResLang("ID_OPT_ARROW", "插入箭頭");
	extfun.setResLang("ID_OPT_RECTANGLE", "插入矩形");
	extfun.setResLang("ID_OPT_CIRCLE", "插入圓形");
	extfun.setResLang("ID_OPT_CHECKMARK", "Add checkmark");
	extfun.setResLang("ID_PAGE_PREVIOUSMOST", "跳至第一頁");
	extfun.setResLang("ID_PAGE_CURRENTPAGE", "");
	extfun.setResLang("ID_PAGE_TOTALPAGE", "");
	extfun.setResLang("ID_PAGE_NEXT", "跳至下一頁");
	extfun.setResLang("ID_PAGE_NEXTMOST", "跳至最後一頁");
	extfun.setResLang("ID_ZOOM_INVERSEPAPER", "紙張方向更改");
	extfun.setResLang("ID_REPORT_CLOSE", "關閉報表");
	extfun.setResLang("ID_REPORT_CLOSEALL", "關閉所有報表");
	extfun.setResLang("ID_OPT_PARAMETERS", "輸入參數");
	extfun.setResLang("ID_OPT_SEARCH", "查找...");
	extfun.setResLang("ID_VIEW_PAGESETUP", "頁面設置");
	extfun.setResLang("ID_VIEW_REPORT_EXPLORER", "查看報表Tree");
	extfun.setResLang("ID_CLOSE_REPORT_EXPLORER", "Close the tree");
	extfun.setResLang("ID_VIEW_REPORT_THUMBNAIL", "显示缩略图");
	extfun.setResLang("ID_CLOSE_REPORT_THUMBNAIL", "Close the thumbnail");
	extfun.setResLang("ID_EXPORT_XLSX", "XLSX 保存");
	extfun.setResLang("IDS_MSG_PRINT_JOB_SUCCESS", "輸出成功完成");
	extfun.setResLang("IDS_MESSAGE_COPY_CLIPBOARD", "已經複製到了剪貼板上 。");
	extfun.setResLang("ID_VIEW_NORMAL", "實際大小");
	extfun.setResLang("ID_VIEW_FITTOFRAME", "適合畫面");
	extfun.setResLang("ID_VIEW_FITTOWIDTH", "適合寬度");
	extfun.setResLang("ID_VIEW_FITTOCONTENTS", "適合可見");
	extfun.setResLang("ID_VIEW_PRINTSIZE", "列印大小");
	extfun.setResLang("ID_VIEW_SINGLE_PAGE", "單頁");
	extfun.setResLang("ID_VIEW_SINGLE_PAGE_CONTINUOUS", "單頁連續");
	extfun.setResLang("ID_VIEW_DOUBLE_PAGE", "兩頁");
	extfun.setResLang("ID_VIEW_DOUBLE_PAGE_CONTINUOUS", "兩頁連續");
	extfun.setResLang("ID_VIEW_CONTINUOUS", "連續");
	extfun.setResLang("ID_SCREENTOOL_HAND", "手形工具");
	extfun.setResLang("ID_SCREENTOOL_EDIT", "編輯工具");
	extfun.setResLang("ID_SCREENTOOL_TEXTSELECT", "文本選擇模式");
	extfun.setResLang("ID_SCREENTOOL_MULTISCREENGUIDE", "Guide mode");
	extfun.setResLang("ID_MENU_SAVEASIMAGE", "另存圖片...");
	extfun.setResLang("ID_MENU_SAVEASAUDIO", "將音頻另存為...");
	extfun.setResLang("ID_MENU_INITIALIZEINPUTDATA", "初始化輸入資料");
	extfun.setResLang("ID_MENU_DELETE", "刪除");
	extfun.setResLang("ID_MENU_EDIT", "更改屬性");
	extfun.setResLang("ID_MENU_DONOTPRINT", "不列印");
	extfun.setResLang("ID_MENU_CHANGE_LABEL", "轉成標簽");
	extfun.setResLang("ID_MENU_CHANGE_IMAGE", "轉成圖像");
	extfun.setResLang("ID_MENU_CHANGE_BARCODE", "轉成條碼");
	extfun.setResLang("ID_MENU_CHANGE_PDF417", "轉成 PDF417 條碼");
	extfun.setResLang("ID_MENU_CHANGE_HTML", "轉成 HTML");
	extfun.setResLang("ID_MENU_CHANGE_QRBARCODE", "轉成 QR 條碼");
	extfun.setResLang("ID_MENU_CHANGE_DATAMATRIX", "轉成 DataMatrix 條碼");
	extfun.setResLang("ID_MENU_CHARTEDIT", "可旋轉");
	extfun.setResLang("IDS_MSG_COMP_EDIT", "屬性編輯");
	extfun.setResLang("IDS_MSG_COMP_MOVE", "移動");
	extfun.setResLang("IDS_MSG_COMP_INPUT", "輸入");
	extfun.setResLang("IDS_MSG_COMP_LINK", "鏈結");
	extfun.setResLang("IDS_MSG_COMP_POSSIBLE", "可能");
	extfun.setResLang("IDS_MSG_COMP_IMPOSSIBLE", "不可能");
	extfun.setResLang("IDS_MSG_COMP_NAME_RECTANGLE", "矩形");
	extfun.setResLang("IDS_MSG_COMP_NAME_ELLIPSE", "橢圓");
	extfun.setResLang("IDS_MSG_COMP_NAME_LINE", "線條");
	extfun.setResLang("IDS_MSG_COMP_NAME_ARROW", "箭頭");
	extfun.setResLang("IDS_MSG_COMP_NAME_CHART", "圖表");
	extfun.setResLang("IDS_MSG_COMP_NAME_MEMO_LABEL", "Memo標籤");
	extfun.setResLang("IDS_MSG_COMP_NAME_LABEL", "標籤");
	extfun.setResLang("IDS_MSG_COMP_NAME_BARCODE", "條碼");
	extfun.setResLang("IDS_MSG_COMP_NAME_BARCODE2", "2維條碼");
	extfun.setResLang("IDS_MSG_COMP_NAME_IMAGE", "圖片");
	extfun.setResLang("IDS_MSG_OUTPUT_INFO", "信息");
	extfun.setResLang("IDS_MSG_OUTPUT_DEBUG", "驗證");
	extfun.setResLang("IDS_MSG_OUTPUT_ERROR", "問題");
	extfun.setResLang("IDS_MSG_OUTPUT_ALL", "全部");
	extfun.setResLang("IDS_MSG_COMP_NAME_MEMO_CHECKMARK", "CheckMark");
	extfun.setResLang("IDS_OZFONT_PLAIN", "常規");
	extfun.setResLang("IDS_OZFONT_ITALIC", "傾斜");
	extfun.setResLang("IDS_OZFONT_BOLD", "加粗");
	extfun.setResLang("IDS_OZFONT_BOLDITALIC", "加粗傾斜");
	extfun.setResLang("IDS_DYN_CENTER", "中間");
	extfun.setResLang("IDS_DYN_LEFT", "左");
	extfun.setResLang("IDS_DYN_RIGHT", "右");
	extfun.setResLang("IDS_DYN_TOP", "上");
	extfun.setResLang("IDS_DYN_BOTTOM", "下");
	extfun.setResLang("IDS_DYN_NONE", "無");
	extfun.setResLang("IDS_DYN_IMG_NORMAL", "一般");
	extfun.setResLang("IDS_DYN_IMG_CENTER", "中間");
	extfun.setResLang("IDS_DYN_IMG_FIT", "固定");
	extfun.setResLang("IDS_DYN_IMG_TILE", "TILE");
	extfun.setResLang("IDS_DYN_IMG_FITBYWIDTH", "橫向固定");
	extfun.setResLang("IDS_DYN_IMG_FITBYHEIGHT", "縱向固定");
	extfun.setResLang("IDS_DYN_IMG_ISOTROPIC", "同一比例");
	extfun.setResLang("IDS_DYN_IMG_TOPCENTER", "靠上、居中");
	extfun.setResLang("IDS_DYN_IMG_TOPRIGHT", "靠上、居中");
	extfun.setResLang("IDS_DYN_IMG_MIDDLELEFT", "居中、靠左");
	extfun.setResLang("IDS_DYN_IMG_MIDDLERIGHT", "居中、向右");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMLEFT", "靠下、靠左");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMCENTER", "靠下、居中");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMRIGHT", "靠下、靠右");
	extfun.setResLang("IDS_DYN_IMG_FITBYWIDTH_CENTER", "橫向固定、居中");
	extfun.setResLang("IDS_DYN_IMG_FITBYHEIGHT_CENTER", "縱向固定、居中");
	extfun.setResLang("IDS_DYN_IMG_ISOTROPIC_CENTER", "同一比例、居中");
	extfun.setResLang("IDS_DYN_TRUE", "是");
	extfun.setResLang("IDS_DYN_FALSE", "不是");
	extfun.setResLang("IDS_DYN_HORIZONTAL", "水平");
	extfun.setResLang("IDS_DYN_VERTICAL", "垂直");
	extfun.setResLang("IDS_DYN_SHAPE_SLASH", "減少");
	extfun.setResLang("IDS_DYN_SHAPE_BACKSLASH", "逆減");
	extfun.setResLang("IDS_QRENCODING_UTF8", "UTF-8");
	extfun.setResLang("IDS_QRENCODING_ANSI", "ANSI");
	extfun.setResLang("IDS_QRECC_L", "L");
	extfun.setResLang("IDS_QRECC_M", "M");
	extfun.setResLang("IDS_QRECC_Q", "Q");
	extfun.setResLang("IDS_QRECC_H", "H");
	extfun.setResLang("IDS_VERIFYQRCODE_NOTPRINTED", "這份文件不是原始的列印文件。請掃描列印文件上的 QR Code 以進行防篡改驗證。");
	extfun.setResLang("IDS_NO_LINE_START", "!),.:;?]}¨•ˇˉ―‖’”…∶、。〃々〉》」』】〕〗！＂＇），．：；？］｀｜｝～￠");
	extfun.setResLang("IDS_NO_LINE_END", "([{•‘“〈《「『【〔〖（．［｛￡￥");
	extfun.setResLang("IDS_MSG_OVERWRITE", "文檔已經存在。\n您要取代它嗎？");
	extfun.setResLang("IDS_MSG_SAVE", "存儲檔案");
	extfun.setResLang("ID_PAGE_PREVIOUS2", "前一頁");
	extfun.setResLang("ID_PAGE_NEXT2", "下一頁");
	extfun.setResLang("ID_ZOOM_RESET2", "還原");
	extfun.setResLang("ID_ZOOM_IN2", "放大");
	extfun.setResLang("ID_ZOOM_OUT2", "縮小");
	extfun.setResLang("ID_MENU_DONOTPRINT2", "列印");
	extfun.setResLang("ID_MENU_CHARTEDIT2", "取消編輯模式");
	extfun.setResLang("IDS_PRINT_RANGE_ERROR", "列印范圍錯誤。");
	extfun.setResLang("IDS_PRINT_RANGE_EMPTY", "未輸入列印范圍。");
	extfun.setResLang("IDS_EXCEL_RANGE_ERROR", "行范圍錯誤。");
	extfun.setResLang("IDS_EXCEL_RANGE_EMPTY", "未輸入行范圍。");
	extfun.setResLang("IDS_HTML_VERSION", "None");
	extfun.setResLang("IDC_INVALID_PASSWORD", "因為設置不允許的密碼文字所以保存時不進行密碼保護.");
	extfun.setResLang("ID_COMMENT_HIDE", "輸入模式");
	extfun.setResLang("ID_COMMENT_PEN", "鉛筆");
	extfun.setResLang("ID_COMMENT_HPEN", "熒光筆");
	extfun.setResLang("ID_COMMENT_CLEAR", "全部刪除");
	extfun.setResLang("ID_COMMENT_SIZE1", "鉛筆粗細");
	extfun.setResLang("ID_COMMENT_SIZE10", "鉛筆粗細");
	extfun.setResLang("ID_COMMENT_SIZE18", "鉛筆粗細");
	extfun.setResLang("ID_COMMENT_PENCOLOR1", "鉛筆顏色");
	extfun.setResLang("ID_COMMENT_PENCOLOR2", "鉛筆顏色");
	extfun.setResLang("IC_COMMENT_COLOR3", "鉛筆顏色");
	extfun.setResLang("ID_COMMENT_PENCOLOR3", "鉛筆顏色");
	extfun.setResLang("ID_COMMENT_ERASERPEN", "橡皮擦");
	extfun.setResLang("ID_SCREENTOOL_COMMENT", "注解模式");
	extfun.setResLang("ID_COMMENT_PENCOLOR4", "鉛筆顏色");
	extfun.setResLang("ID_COMMENT_PENCOLOR5", "鉛筆顏色");
	extfun.setResLang("ID_COMMENT_PENCOLOR6", "鉛筆顏色");
	extfun.setResLang("ID_COMMENT_DRAW_BORDER", "Draw border");
	extfun.setResLang("ID_COMMENT_FILL_BACKGROUND", "Fill background");
	extfun.setResLang("IDS_COMMENT_PEN_TITLE", "鉛筆粗細 & 顏色");
	extfun.setResLang("IDS_COMMENT_HPEN_TITLE", "熒光筆粗細 & 顏色");
	extfun.setResLang("IDS_REMOVE_COMMENT", "是否刪除所有注解？");
	extfun.setResLang("IDS_COMMENT_PEN", "");
	extfun.setResLang("IDS_COMMENT_HPEN", "");
	extfun.setResLang("IDS_COMMENT_REMOVE_ALL", "");
	extfun.setResLang("IDS_COMMENT_DRAW_BORDER_TITLE", "Border thickness && color");
	extfun.setResLang("IDS_COMMENT_FILL_BACKGROUND_TITLE", "Background color");
	extfun.setResLang("ID_TEXT_COPY", "復制");
	extfun.setResLang("ID_TEXT_SELECT_ALL", "全部選擇");
	extfun.setResLang("ID_TEXT_DESELECT_ALL", "解除全部選擇");
	extfun.setResLang("ID_START_EDITING", "Start Input");
	extfun.setResLang("ID_END_EDITING", "End Input");
	extfun.setResLang("ID_COPYINPUTDATA_JSON", "複製輸入資料 (json)");
	extfun.setResLang("ID_COPYINPUTDATA_XML", "複製輸入資料 (xml)");
	extfun.setResLang("ID_COPY_PROCESSOR_ID", "Processor ID 資料");
	extfun.setResLang("IDS_MSG_PROGRESS_BINDING", "正在綁定報表.");
	extfun.setResLang("ID_MENU_SAVETABLEASPNG", "表格保存 (PNG)...");
	extfun.setResLang("ID_MENU_SAVETABLEASHTML", "表格保存 (HTML)...");
	extfun.setResLang("ID_MENU_SHOW_SAVED_HISTORY", "保存历史查询");
	extfun.setResLang("ID_HISTORY_SAVED", "保存历史");
	extfun.setResLang("ID_HISTORY_DETAIL", "项目别详细历史");
	extfun.setResLang("ID_HISTORY_BACK", "以前");
	extfun.setResLang("ID_HISTORY_REVERT", "Revert");
	extfun.setResLang("ID_HISTORY_COMPLETE", "完成");
	extfun.setResLang("IDS_BMT_START_SVG_BIND", "開始系結:");
	extfun.setResLang("IDS_BMT_SVG_BINDING", "系結中:");
	extfun.setResLang("IDS_BMT_END_SVG_BIND", "系結完成:");
	extfun.setResLang("IDS_MSG_LOADER_READ_PAGE_FROM_REMOTE", "正在從伺服器讀取頁面。");
	extfun.setResLang("ID_OPT_SHOWCONSOLE", "查看控制臺...");
	extfun.setResLang("IDS_MSG_SCAN_ID_FAIL", "The ID card image cannot be recognized. Click the shoot button to shoot again.");
	extfun.setResLang("IDS_OPT_SAVEAS_DEFAULT", "基本選項");
	extfun.setResLang("IDS_OPT_SAVEAS", "保存選項");
	extfun.setResLang("IDS_OPT_SAVE_WAY_TXT", "Save report after binding per one page/pages.");
	extfun.setResLang("IDS_OPT_SAVE_WAY_ONEPAGE", "Save Per OnePage");
	extfun.setResLang("IDS_OPT_SAVE_WAY_EACHPAGE", "Save Per Pages");
	extfun.setResLang("IDS_OPT_SAVE_WAY", "保存方式");
	extfun.setResLang("IDS_OPT_SAVE_ACTION", "Action");
	extfun.setResLang("IDS_OPT_SAVE_MULTIDOC", "多文檔");
	extfun.setResLang("IDS_OPT_SAVE_AREA", "保存領域");
	extfun.setResLang("IDS_OPT_SAVE_COMPONENT", "組件");
	extfun.setResLang("IDS_OPT_SAVE_LINK_INFO", "保存鏈結");
	extfun.setResLang("IDS_OPT_ACTION_AFTER_SAVE", "Action after save");
	extfun.setResLang("IDS_OPT_SAVE_ONEFILE", "保存為一個檔");
	extfun.setResLang("IDS_OPT_SAVE_ALLFILE", "保存所有文檔");
	extfun.setResLang("IDS_OPT_ALLPAGE", "全部頁");
	extfun.setResLang("IDS_OPT_CURRENTPAGE", "當前頁");
	extfun.setResLang("IDS_OPT_SELECTEDPAGE", "被選頁");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE", "頁碼範圍 : ");
	extfun.setResLang("IDS_OPT_COMPONENT_LABEL", "設定要保存的組件");
	extfun.setResLang("IDS_OPT_LABEL", "標籤");
	extfun.setResLang("IDS_OPT_IMAGE", "圖片");
	extfun.setResLang("IDS_OPT_BARCODE", "條碼");
	extfun.setResLang("IDS_OPT_PDF417", "PDF417 條碼");
	extfun.setResLang("IDS_OPT_QR_BARCODE", "QR 條碼");
	extfun.setResLang("IDS_OPT_HTML", "HTML");
	extfun.setResLang("IDS_OPT_CHART", "圖表");
	extfun.setResLang("IDS_OPT_LINE", "線條");
	extfun.setResLang("IDS_OPT_CIRCLE", "圓形");
	extfun.setResLang("IDS_OPT_RECTANGLE", "矩形");
	extfun.setResLang("IDS_OPT_ARROW", "箭頭");
	extfun.setResLang("IDS_OPT_URL_LINK", "URL鏈結");
	extfun.setResLang("IDS_OPT_LIST_LINK", "目錄鏈結");
	extfun.setResLang("IDS_OPT_PDF_SAVE", "PDF 保存選項");
	extfun.setResLang("IDS_OPT_DOC_IMFOR", "文檔信息");
	extfun.setResLang("IDS_OPT_OPEN_PROTECT", "限制打開");
	extfun.setResLang("IDS_OPT_EDIT_PROTECT", "限制修改");
	extfun.setResLang("IDS_OPT_USER_RIGHT", "用戶訪問許可權");
	extfun.setResLang("IDS_OPT_TITLE", "標題");
	extfun.setResLang("IDS_OPT_WRITER", "作者");
	extfun.setResLang("IDS_OPT_SUBJECT", "主題");
	extfun.setResLang("IDS_OPT_KEYWORD", "關鍵字");
	extfun.setResLang("IDS_OPT_APPLICATION", "應用程式");
	extfun.setResLang("IDS_OPT_USER_PW", "打開口令");
	extfun.setResLang("IDS_OPT_USER_PW_CONFIRM", "確認打開口令");
	extfun.setResLang("IDS_OPT_MASTER_PW", "修改口令");
	extfun.setResLang("IDS_OPT_MASTER_PW_CONFIRM", "確認修改口令");
	extfun.setResLang("IDS_OPT_PRINT_PERMIT", "允許列印");
	extfun.setResLang("IDS_OPT_CONTENTS_COPY", "複製內容");
	extfun.setResLang("IDS_OPT_SAVEIMG_TOCHART", "圖表保存為圖片");
	extfun.setResLang("IDS_OPT_FONT_INCLUDE", "폰트 포함");
	extfun.setResLang("IDS_OPT_PRINT", "列印");
	extfun.setResLang("IDS_OPT_PRINT_COUNT", "列印份數");
	extfun.setResLang("IDS_OPT_PRINT_SCOPE", "列印範圍");
	extfun.setResLang("IDS_OPT_PRINT_RULE", "列印方式");
	extfun.setResLang("IDS_OPT_COUNT", "份");
	extfun.setResLang("IDS_OPT_PRINT_ONEPAGE", "逐份列印");
	extfun.setResLang("IDS_OPT_PRINT_ALL_REPORT", "列印所有文件");
	extfun.setResLang("IDS_OPT_ALL", "全部");
	extfun.setResLang("IDS_OPT_CHOOSE_PAGE", "頁碼範圍");
	extfun.setResLang("IDS_OPT_PRINT_FITTOPAGE", "按紙張大小縮放");
	extfun.setResLang("IDS_OPT_DEVIDE_PRINT", "分開列印");
	extfun.setResLang("IDS_OPT_DEVIDE_PRINT_TOFITPAPER", "按紙張分開列印");
	extfun.setResLang("IDS_TOGETHER_PRINT", "多頁列印");
	extfun.setResLang("IDS_OPT_PAGECOUNT_TOPRINT", "一張紙上列印的頁數");
	extfun.setResLang("IDS_OPT_PRINT_ORDER", "列印順序");
	extfun.setResLang("IDS_OPT_HORIZON", "水平");
	extfun.setResLang("IDS_OPT_VERTICAL", "垂直");
	extfun.setResLang("IDS_OPT_PRINT_DIRECTION", "列印方向");
	extfun.setResLang("IDS_OPT_PORTRAIT", "縱向");
	extfun.setResLang("IDS_OPT_LANDSCAPE", "橫向");
	extfun.setResLang("IDS_OPT_OPTION", "選項");
	extfun.setResLang("IDS_OPT_CONFIRM", "確認");
	extfun.setResLang("IDS_OPT_CANCEL", "取消");
	extfun.setResLang("IDS_OPT_CLOSE", "Close");
	extfun.setResLang("IDS_OPT_SAVE", "저장");
	extfun.setResLang("IDS_OPT_OZD_SAVE_OPTION", "保存選項");
	extfun.setResLang("IDS_OPT_PASSWORD", "密碼");
	extfun.setResLang("IDS_OPT_MEMOADD_OK", "包含編輯內容");
	extfun.setResLang("IDS_OPT_SAVE_ALLREPORT", "保存所有報表");
	extfun.setResLang("IDS_OPT_INCLUDE_IMG", "嵌入圖片");
	extfun.setResLang("IDS_OPT_FILE_TYPE", "文件類型");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE", "Excel 保存選項");
	extfun.setResLang("IDS_OPT_WORD_SAVE", "Word 保存選項");
	extfun.setResLang("IDS_OPT_DOCX_SAVE", "Word 保存選項");
	extfun.setResLang("IDS_OPT_PPT_SAVE", "PowerPoint 保存選項");
	extfun.setResLang("IDS_OPT_HTML_SAVE", "HTML 保存選項");
	extfun.setResLang("IDS_OPT_CSV_SAVE", "CSV 保存選項");
	extfun.setResLang("IDS_OPT_TEXT_SAVE", "TEXT 保存選項");
	extfun.setResLang("IDS_OPT_JPG_SAVE", "JPG 保存選項");
	extfun.setResLang("IDS_OPT_TIFF_SAVE", "TIFF 保存選項");
	extfun.setResLang("IDS_OPT_HWP_SAVE", "Hangul Option");
	extfun.setResLang("IDS_OPT_HWP97_SAVE", "Hangul97 Option");
	extfun.setResLang("IDS_OPT_MHT_SAVE", "MHT 保存選項");
	extfun.setResLang("IDS_OPT_SAVE_FORM", "分隔標記");
	extfun.setResLang("IDS_OPT_PAGE", "頁");
	extfun.setResLang("IDS_OPT_FONT", "字體");
	extfun.setResLang("IDS_OPT_FORMAT", "格式");
	extfun.setResLang("IDS_OPT_AUTO_FIT", "自動調整");
	extfun.setResLang("IDS_OPT_CELL_MINIMUM_SIZE_CELL", "單元格最小值");
	extfun.setResLang("IDS_OPT_SAVE_MODE", "保存類型");
	extfun.setResLang("IDS_OPT_KEEP_FORM_ATTR", "保持報表原樣，屬性");
	extfun.setResLang("IDS_OPT_IGNORE_COLOR_OUTLINE_CELL", "不含顏色，邊框，單元格合併");
	extfun.setResLang("IDS_OPT_REMOVE_CELL_AFTERDIVIDE", "拆分後刪除周邊單元格");
	extfun.setResLang("IDS_OPT_SAVE_SHEET_PER_COLPAGE", "一列的頁保存為一個工作表");
	extfun.setResLang("IDS_OPT_SAVE_SHEET_PAGE", "一頁保存為一個工作表");
	extfun.setResLang("IDS_OPT_COLUMN_FIRST", "先行後列");
	extfun.setResLang("IDS_OPT_ROW_FIRST", "先列後行");
	extfun.setResLang("IDS_OPT_REMOVE_PAGE_GAP", "除去頁間空白");
	extfun.setResLang("IDS_OPT_SIZE_COLON", "大小:");
	extfun.setResLang("IDS_OPT_REMOVE_LINE", "刪除行");
	extfun.setResLang("IDS_OPT_EXCLUDE_FIRST_PAGE", "第一頁除外");
	extfun.setResLang("IDS_OPT_ONLY_FIRST_PAGE", "只選第一頁");
	extfun.setResLang("IDS_OPT_ALL_PAGE", "所有頁");
	extfun.setResLang("IDS_OPT_LINE_SCOPE_LINE_NUMBER", "請鍵入行號和/或用逗號(, )\n分隔的行範圍。例如）1-3，5，12");
	extfun.setResLang("IDS_OPT_CHANGE_TXT_TO_INTEGER", "把文本型數位轉換為數值");
	extfun.setResLang("IDS_OPT_APPLY_ONLYLABEL_NUMBER", "只適用數值型標籤");
	extfun.setResLang("IDC_CHECK_APPLY_DATETIMEFORMAT", "Date type text convert to date");
	extfun.setResLang("IDS_OPT_CHANGE_AS_NORMAL", "轉換為常規(單元格格式)");
	extfun.setResLang("IDS_OPT_FONT_COLON", "字體:");
	extfun.setResLang("IDS_OPT_WIDTH", "寬度");
	extfun.setResLang("IDS_OPT_HEIGHT", "高度");
	extfun.setResLang("IDS_OPT_SAVE_MHT_TYPE", "以mht格式保存 （支援office XP或更高版本）");
	extfun.setResLang("IDS_OPT_TABLE_SAVE_WAY", "表格保存方式");
	extfun.setResLang("IDS_OPT_TABLE_TYPE_WAY", "保存為表格           ");
	extfun.setResLang("IDS_OPT_BAND_SAVE_WAY", "Band保存方式");
	extfun.setResLang("IDS_OPT_BAND_SAVE_PAGE", "將頁眉/頁腳Band保存在頁眉/頁腳");
	extfun.setResLang("IDS_OPT_PPT_SAVE_WAY", "PowerPoint 保存方式");
	extfun.setResLang("IDS_OPT_MHTD_SAVE_PAGE", "以mht格式保存（支援office XP或更高版本）");
	extfun.setResLang("IDS_OPT_FONT_SIZE_SETTING", "設定字體大小");
	extfun.setResLang("IDS_OPT_PAGE_BETWEEN", "頁間距");
	extfun.setResLang("IDS_OPT_PER_PAGE_SAVE", "分頁保存");
	extfun.setResLang("IDS_OPT_LINE_COUNT_COLON", "行數 :");
	extfun.setResLang("IDS_OPT_OFFSET_COLON", "偏移 :");
	extfun.setResLang("IDS_OPT_STARTPOINT_HTMLDOC", "指定HTML文檔的初始坐標");
	extfun.setResLang("IDS_OPT_ENCODING_COLON", "編碼 : ");
	extfun.setResLang("IDS_OPT_X_AXIS", "X軸");
	extfun.setResLang("IDS_OPT_Y_AXIS", "Y軸");
	extfun.setResLang("IDS_OPT_OFFSET", "偏移");
	extfun.setResLang("IDS_OPT_SEPARATION", "分隔");
	extfun.setResLang("IDS_OPT_SEPARATOR", "分隔符號");
	extfun.setResLang("IDS_OPT_USER_DEFINE", "自定義");
	extfun.setResLang("IDS_OPT_SEPARATION_TYPE", "分隔標記");
	extfun.setResLang("IDS_OPT_PAGE_BRACKET", "<PAGE>");
	extfun.setResLang("IDS_OPT_SET_PAGELINE", "設定空白行數");
	extfun.setResLang("IDS_OPT_CHAR_NUMBER", "數位文字");
	extfun.setResLang("IDS_OPT_ADD_SEPARATOR", "添加千位分隔符號");
	extfun.setResLang("IDS_OPT_REMOVE_SEPARATOR", "去除千位分隔符號");
	extfun.setResLang("IDS_OPT_PAGE_SEPARATION", "分页");
	extfun.setResLang("IDS_OPT_LABEL_SAVE", "標籤保存方式");
	extfun.setResLang("IDS_OPT_LABEL_SIZE", "固定標籤尺寸");
	extfun.setResLang("IDS_OPT_POSITION_SAVE", "位置保存方式");
	extfun.setResLang("IDS_OPT_VERTREL_TOPARA", "將縱向設定為文段");
	extfun.setResLang("IDS_OPT_BACKGROUND_BAND", "Save background band to background page");
	extfun.setResLang("IDS_OPT_TITLE_COLON", "標題 :");
	extfun.setResLang("IDS_OPT_DISPLAY_OPTION", "顯示選項");
	extfun.setResLang("IDS_OPT_GRIDLINES", "顯示格線");
	extfun.setResLang("IDS_OPT_ENCODING_WAY", "編碼方式");
	extfun.setResLang("IDS_OPT_ENCODING_G3", "G3");
	extfun.setResLang("IDS_OPT_ENCODING_G4", "G4");
	extfun.setResLang("IDS_OPT_ENCODING_SAVEAS_ONEFILE", "保存在一個檔");
	extfun.setResLang("IDS_OPT_RATIO", "比例");
	extfun.setResLang("IDS_OPT_ZOOM_INOUT", "放大/縮小");
	extfun.setResLang("IDS_OPT_SET_DPI", "適合解析度的尺寸");
	extfun.setResLang("IDS_OPT_DPI", "解析度");
	extfun.setResLang("IDS_OPT_SIZE", "大小");
	extfun.setResLang("IDS_OPT_SAVE_RATIO", "保存縮放");
	extfun.setResLang("IDS_OPT_COMPRESSION", "壓縮");
	extfun.setResLang("IDS_OPT_QUALITY", "品質");
	extfun.setResLang("IDS_OPT_USE_INDENT", "使用縮進功能");
	extfun.setResLang("IDS_OPT_DATA_SAVE", "資料保存");
	extfun.setResLang("IDS_OPT_FIND_WHAT", "尋找目標:");
	extfun.setResLang("IDS_OPT_MATCH_WHOLE_WORD", "全字須相符");
	extfun.setResLang("IDS_OPT_MATCH_CASE", "大小寫須相符");
	extfun.setResLang("IDS_OPT_DIRECTION", "方向");
	extfun.setResLang("IDS_OPT_SEARCH_UP", "向上");
	extfun.setResLang("IDS_OPT_SEARCH_DOWN", "向下");
	extfun.setResLang("IDS_OPT_NEXT", "找下一個");
	extfun.setResLang("IDS_OPT_REFRESH_REPORT", "報表刷新");
	extfun.setResLang("IDS_OPT_INTERVAL", "週期");
	extfun.setResLang("IDS_OPT_HH", "時");
	extfun.setResLang("IDS_OPT_MM", "分");
	extfun.setResLang("IDS_OPT_SS", "秒");
	extfun.setResLang("IDS_OPT_REFRESH_NOW", "刷新");
	extfun.setResLang("IDS_OPT_START", "開始");
	extfun.setResLang("IDS_OPT_STOP", "停止");
	extfun.setResLang("IDS_OPT_LEFT_COLON", "左:");
	extfun.setResLang("IDS_OPT_RIGHT_COLON", "右:");
	extfun.setResLang("IDS_OPT_TOP_COLON", "上:");
	extfun.setResLang("IDS_OPT_BOTTOM_COLON", "下:");
	extfun.setResLang("IDS_OPT_PAGE_SETUP", "頁面設定");
	extfun.setResLang("IDS_OPT_MARGIN", "頁邊距");
	extfun.setResLang("IDS_OPT_UNIT", "使用單位系");
	extfun.setResLang("IDS_OPT_UNIT_COLON", "單位 :");
	extfun.setResLang("IDS_OPT_MARGIN_OPTION", "頁邊距選項");
	extfun.setResLang("IDS_OPT_MARGIN_DEFAULT", "使用預設值");
	extfun.setResLang("IDS_OPT_MARGIN_AUTO_ADJUST", "自動調整");
	extfun.setResLang("IDS_OPT_HTML_VERSION", "版本");
	extfun.setResLang("IDS_OPT_HTML_VERSION_COLON", "HTML 版本 :");
	extfun.setResLang("IDS_OPT_TOTAL", "全部");
	extfun.setResLang("IDS_OPT_REPORT_STRUCTURE", "查看報表結構");
	extfun.setResLang("IDS_OPT_LABEL_FORMAT", "標籤格式");
	extfun.setResLang("IDS_OPT_PARAGRAPH", "段落");
	extfun.setResLang("IDS_OPT_FILL", "填充");
	extfun.setResLang("IDS_OPT_LINECOLOR", "邊框");
	extfun.setResLang("IDS_OPT_ETC", "其他");
	extfun.setResLang("IDS_OPT_ALIGNMENT", "對齊");
	extfun.setResLang("IDS_OPT_TXT_DIRECTION", "文字方向");
	extfun.setResLang("IDS_OPT_INTERNAL_MARGIN", "邊距");
	extfun.setResLang("IDS_OPT_PREVIEW", "預覽");
	extfun.setResLang("IDS_OPT_HORIZON_COLON", "水平 :");
	extfun.setResLang("IDS_OPT_VERTICAL_COLON", "垂直 :");
	extfun.setResLang("IDS_OPT_LINE_SPACE_COLON", "行距 :");
	extfun.setResLang("IDS_OPT_INDENT_COLON", "縮進 :");
	extfun.setResLang("ID_OPT_PARAMETERS_TITLE_LABEL", "更改參數值");
	extfun.setResLang("IDS_OPT_EXIT", "結束");
	extfun.setResLang("IDS_OPT_OZZPASSWORD", "密碼");
	extfun.setResLang("IDS_OPT_OZZPASSWORD_CHECK", "確認密碼");
	extfun.setResLang("IDS_OPT_ID", "用戶名");
	extfun.setResLang("IDS_OPT_SECURITY", "安全");
	extfun.setResLang("IDS_OPT_PRODUCT_INFO", "產品信息");
	extfun.setResLang("IDS_OPT_OZ_INFO", "產品 信息");
	extfun.setResLang("IDS_OPT_ERROR_CODE_COLON", "錯誤代碼:");
	extfun.setResLang("IDS_OPT_GENERAL_MSG_COLON", "訊息:");
	extfun.setResLang("IDS_OPT_VIEW_DETAIL", "詳細查看");
	extfun.setResLang("IDS_OPT_DETAIL_MSG_COLON", "詳細訊息:");
	extfun.setResLang("IDS_OPT_TEXT_CONTROL", "文字控制");
	extfun.setResLang("IDS_OPT_SHRINK_TO_FIT", "縮小字型以適合欄寬");
	extfun.setResLang("IDS_OPT_PASSWORD2", "確認口令");
	extfun.setResLang("IDS_OPT_DM_BARCODE", "DataMatrix 條碼");
	extfun.setResLang("IDS_OPT_FONT_STYLE_COLON", "字形:");
	extfun.setResLang("IDS_OPT_COLOR_COLON", "顏色 :");
	extfun.setResLang("IDS_OPT_INTERVAL_COLON", "字間距  :");
	extfun.setResLang("IDS_OPT_STRETCH_COLON", "Stretch :");
	extfun.setResLang("IDS_OPT_EFFECT", "效果");
	extfun.setResLang("IDS_OPT_UNDERLINE", "下劃線");
	extfun.setResLang("IDS_OPT_STRIKEOUT", "刪除線");
	extfun.setResLang("IDS_OPT_DOUBLE_STRIKEOUT", "雙刪除線");
	extfun.setResLang("IDS_OPT_NO_FILL", "無填充");
	extfun.setResLang("IDS_OPT_TRANSPARENCY", "透明度 :");
	extfun.setResLang("IDS_OPT_GRADIENT", "漸變色");
	extfun.setResLang("IDS_OPT_USE_GRADIENT", "使用漸變色");
	extfun.setResLang("IDS_OPT_SLASH", "左斜對角線");
	extfun.setResLang("IDS_OPT_BACK_SLASH", "右斜對角線");
	extfun.setResLang("IDS_OPT_START_POSITION", "起點");
	extfun.setResLang("IDS_OPT_FROM_EDGE", "邊角");
	extfun.setResLang("IDS_OPT_DIRECT", "正方向");
	extfun.setResLang("IDS_OPT_FROM_CENTER", "中心");
	extfun.setResLang("IDS_OPT_REVERSE", "反方向");
	extfun.setResLang("IDS_OPT_THICKNESS_W", "厚度(W) :");
	extfun.setResLang("IDS_OPT_STYLE_Y", "樣式(Y) :");
	extfun.setResLang("IDS_OPT_COLOR_C", "顏色(C) :");
	extfun.setResLang("IDS_OPT_CLIPPING", "剪貼");
	extfun.setResLang("IDS_OPT_WORD_WRAP", "自動換行");
	extfun.setResLang("IDS_OPT_WORD_WRAP_TYPE", "自動換行方式");
	extfun.setResLang("IDS_OPT_IGNORE_SPACE", "忽略空白");
	extfun.setResLang("IDS_OPT_NON_ASCII_WORD", "不允許切斷單詞");
	extfun.setResLang("IDS_OPT_TOOLTIP_TEXT", "工具提示文本...");
	extfun.setResLang("IDS_OPT_BASIC", "Basic");
	extfun.setResLang("IDS_OPT_OUTLINE", "Outline");
	extfun.setResLang("IDS_OPT_3D", "3D");
	extfun.setResLang("IDS_OPT_ENGRAVE", "Engrave");
	extfun.setResLang("IDS_OPT_SEGMENT", "Segments");
	extfun.setResLang("IDS_OPT_HOLLOW", "Hollow");
	extfun.setResLang("IDS_OPT_SHADOW", "Shadow");
	extfun.setResLang("IDS_OPT_IMAGE_STYLE", "樣式 :");
	extfun.setResLang("IDS_OPT_BARCODE_STYLE", "條碼類型 :");
	extfun.setResLang("IDS_OPT_DATA_GAP", "資料間距：");
	extfun.setResLang("IDS_OPT_DATA_POSITION", "資料位置：");
	extfun.setResLang("IDS_OPT_BARCODE_MARGIN", "條碼邊距：");
	extfun.setResLang("IDS_OPT_ALIGN_HORIZONTALLY", "條碼水平對齊：");
	extfun.setResLang("IDS_OPT_RATION_COLON", "比例 :");
	extfun.setResLang("IDS_OPT_PRINTING_SCALE", "列印尺寸：");
	extfun.setResLang("IDS_OPT_ROTATION_COLON", "旋轉 :");
	extfun.setResLang("IDS_OPT_TITLE_GAP", "標題間距：");
	extfun.setResLang("IDS_OPT_TITLE_POSITION", "標題位置：");
	extfun.setResLang("IDS_OPT_BARCODE_ERROR_OPTION", "錯誤顯示選項 :");
	extfun.setResLang("IDS_OPT_DISPLAY_ERROR_DATA", "顯示錯誤資料");
	extfun.setResLang("IDS_OPT_DISPLAY_ERROR_SIZE", "顯示條碼大小錯誤");
	extfun.setResLang("IDS_OPT_DISPLAY_EMPTY_DATA", "顯示空資料");
	extfun.setResLang("IDS_OPT_PDF_IMAGE_STYLE", "圖像類型：");
	extfun.setResLang("IDS_OPT_PDF_ROW_NUMBER", "行數：");
	extfun.setResLang("IDS_OPT_PDF_COL_NUMBER", "列數 :");
	extfun.setResLang("IDS_OPT_PDF_ECC", "修改錯誤 :");
	extfun.setResLang("IDS_OPT_PDF_X_SCALE", "X大小 :");
	extfun.setResLang("IDS_OPT_PDF_Y_SCALE", "Y大小 :");
	extfun.setResLang("IDS_OPT_BORDER_COLOR", "邊緣顏色 :");
	extfun.setResLang("IDS_OPT_BORDER_TRANSPARENCY", "Border Transparency :");
	extfun.setResLang("IDS_OPT_FILL_COLOR", "填充色 :");
	extfun.setResLang("IDS_OPT_THICKNESS", "厚度 :");
	extfun.setResLang("IDS_OPT_SHAPE_NO_FILL", "透明 :");
	extfun.setResLang("IDS_OPT_LINE_TYPE", "線種類 :");
	extfun.setResLang("IDS_OPT_TOOLTIP_TEXT_COLON", "工具提示文本 :");
	extfun.setResLang("IDS_OPT_EDIT_CHART", "圖表編輯");
	extfun.setResLang("IDS_OPT_SHOW_DATA", "查看資料");
	extfun.setResLang("IDS_OPT_EDIT_SHAPE", "圖形編輯");
	extfun.setResLang("IDS_FORCS_RV", "Forcs(R) OZ Report Viewer");
	extfun.setResLang("IDS_OPT_EXCEL_LINE", "線條");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE_TYPE", "保存形式");
	extfun.setResLang("IDS_OPT_JPG_ZOOM_INOUT", "放大/縮小");
	extfun.setResLang("IDS_OPT_ZOOM_INOUT_COLON", "放大/縮小 : ");
	extfun.setResLang("IDS_OPT_QUALITY_COLON", "品質 : ");
	extfun.setResLang("IDS_OPT_TIFF_SIZE", "大小");
	extfun.setResLang("IDS_OPT_PAGELINE", "Line");
	extfun.setResLang("IDS_OPT_WORD_BAND_SAVE_PAGE", "將頁眉/頁腳Band保存在頁眉/頁腳");
	extfun.setResLang("IDS_OPT_PRINT_MULTIDOC", "多文檔");
	extfun.setResLang("ID_PAGE_CONTROL_WINDOW", "選頁窗");
	extfun.setResLang("IDS_OPT_FONT_NAME_COLON", "字體 :");
	extfun.setResLang("IDS_OPT_FONT_OPTION", "選項");
	extfun.setResLang("IDS_OPT_AUTO_SELECTED", "自動調整");
	extfun.setResLang("IDS_OPT_SIDE", "寬度");
	extfun.setResLang("IDS_OPT_LENGTH", "高度");
	extfun.setResLang("IDS_OPT_OTHER", "自定義");
	extfun.setResLang("IDS_OPT_FONT_SAVE_WAY", "字體");
	extfun.setResLang("IDS_OPT_HORIZONTAL_NAVI", "水平");
	extfun.setResLang("IDS_OPT_VERTICAL_NAVI", "垂直");
	extfun.setResLang("IDS_OPT_PNG_SAVE", "PNG 保存選項");
	extfun.setResLang("IDS_OPT_GIF_SAVE", "GIF 保存選項");
	extfun.setResLang("IDS_OPT_REMOVE_LINES", "刪除行");
	extfun.setResLang("IDS_OPT_ENCODING_HDM", "編碼 : ");
	extfun.setResLang("IDS_OPT_SVG_SAVE", "SVG 保存選項");
	extfun.setResLang("IDS_OPT_PDF_CHANGEABLE", "複製內容");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE1", "無");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE2", "注釋, 填寫表單和簽名現有簽名域");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE3", "頁面配置, 填寫表單和簽名現有簽名域");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE4", "除了提取頁面");
	extfun.setResLang("IDS_OPT_SAVE_WAY_BASE", "保存方式");
	extfun.setResLang("IDS_OPT_SAVE_LARGEBUNDLE_BYPAGE", "一頁/分頁保存報表");
	extfun.setResLang("IDS_OPT_SAVE_LARGE_BUNDLE", "保存為一頁");
	extfun.setResLang("IDS_OPT_SAVE_BY_PAGE", "分頁保存");
	extfun.setResLang("IDS_OPT_KEEP_SAVING", "keep saving");
	extfun.setResLang("IDC_TITLE_SECURITY", "限制打開");
	extfun.setResLang("IDC_EDIT_PASSWORD", "打開口令");
	extfun.setResLang("IDC_EDIT_PASSWORD_VERIFY", "確認打開口令");
	extfun.setResLang("IDC_ZIP_GROUP", "壓縮");
	extfun.setResLang("IDC_COMPRESS_ON_SAVE", "壓縮保存");
	extfun.setResLang("IDC_PAPER_SETUP", "紙張設定");
	extfun.setResLang("IDC_CHECK_ADJUST", "按紙張大小縮放");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE_DETAIL", "請鍵入頁碼和/或用逗號分隔的頁碼範圍。");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE_DETAIL2", "(例如：1.3.5-12)");
	extfun.setResLang("IDS_OPT_NEXCEL_SAVE", "Nexcel 保存選項");
	extfun.setResLang("IDS_OPT_NEXCEL_SAVE2", "Nexcel 保存選項(Advanced)");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE2", "Excel 保存選項(Advanced)");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM", "比例");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM_RATIO", "放大/縮小: ");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM_RATIO2", "放大/縮小(%)");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES", "Freeze panes");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_ROW", "Row: ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_COL", "Column: ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_ROW_M", "Row ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_COL_M", "Column ");
	extfun.setResLang("IDC_EDIT_ZIP_PASSWORD", "打開口令");
	extfun.setResLang("IDC_EDIT_ZIP_PASSWORD_VERIFY", "確認打開口令");
	extfun.setResLang("IDS_OPT_BMP_SAVE", "BMP 保存選項");
	extfun.setResLang("IDS_OPT_RTF_SAVE", "RTF 保存選項");
	extfun.setResLang("IDS_OPT_SELECTREPORT", "指定報表:");
	extfun.setResLang("IDS_OPT_SELECTREPORT2", "選擇報表......");
	extfun.setResLang("IDS_OPT_SELECTREPORT_TITLE", "選擇報表");
	extfun.setResLang("IDS_OPT_CHECK_SELECT_ALL", "全部選擇");
	extfun.setResLang("ID_PAGE_CONTROL_NAVIGATOR", "選頁窗");
	extfun.setResLang("ID_PARAMETER_TOOLBAR", "Parameter toolbar");
	extfun.setResLang("IDS_OPT_ENCODING_JPG", "JPG");
	extfun.setResLang("IDS_OPT_MARGIN_COLON", "邊距 :");
	extfun.setResLang("IDS_OPT_SEARCH", "查找");
	extfun.setResLang("IDS_CONSOLE", "主控臺");
	extfun.setResLang("IDS_LICENSE_ERROR_TITLE", "Failed to verify licensing.");
	extfun.setResLang("IDS_LICENSE_ERROR_EXPIRED", "The license has been expired.");
	extfun.setResLang("IDS_LICENSE_ERROR_VERSION", "The license does not match with software version.");
	extfun.setResLang("IDS_LICENSE_ERROR_CERT", "Failed to verify the certificate.");
	extfun.setResLang("IDS_LICENSE_ERROR_FILENOTFOUND", "Cannot find license file.");
	extfun.setResLang("IDS_LICENSE_ERROR_DOMAIN", "The license does not match with domain.");
	extfun.setResLang("IDS_OPT_CELL_SAVE", "Cell 保存選項");
	extfun.setResLang("IDS_OPT_CELL_SAVE2", "Cell 保存選項(Advanced)");
	extfun.setResLang("IDS_SELECT_FILE", "Select File");
	extfun.setResLang("IDS_SHOOT", "Camera");
	extfun.setResLang("IDS_SHOOT_OR_SELECT_FILE", "Shoot or Select File");
	extfun.setResLang("IDS_IMAGE_MERGE_ITEM", "Combine photos");
	extfun.setResLang("IDS_IMAGE_EDIT_TITLE", "Add Photo");
	extfun.setResLang("IDS_IMAGE_EDIT_DONE", "Done");
	extfun.setResLang("IDS_IMAGE_EDIT_CANCEL", "Cancel");
	extfun.setResLang("IDS_DLG_EDIT", "編輯");
	extfun.setResLang("IDS_THUMBNAIL_ALLOWCLOSE", "關閉報表");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_LEFT", "文本左对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_CENTER", "居中");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_RIGHT", "文本右对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_HDIST", "水平分散对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_HJUSTIFY", "水平两端对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_TOP", "顶端对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_MIDDLE", "垂直居中");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_BOTTOM", "底端对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_VDIST", "垂直分散对齐");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_VJUSTIFY", "垂直两端对齐");
	extfun.setResLang("IDS_LAYOUT_MOVE_LEFT", "Text direction left");
	extfun.setResLang("IDS_LAYOUT_MOVE_TOP", "Text direction top");
	extfun.setResLang("IDS_LAYOUT_MOVE_RIGHT", "Text direction right");
	extfun.setResLang("IDS_LAYOUT_MOVE_BOTTOM", "Text direction bottom");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_HORIZONTAL", "HORIZONTAL");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_VERTICAL", "VERTICAL");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_CLOCKWISE", "CLOCKWISE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_COUNTERCLOCKWISE", "COUNTERCLOCKWISE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_VERTICAL_2BYTE", "VERTICAL_2BYTE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_HORIZONTAL_2BYTE", "HORIZONTAL_2BYTE");
	extfun.setResLang("IDS_BORDER_TOP", "上框线");
	extfun.setResLang("IDS_BORDER_MIDDLE", "内部横框线");
	extfun.setResLang("IDS_BORDER_BOTTOM", "下框线");
	extfun.setResLang("IDS_BORDER_LEFT", "左框线");
	extfun.setResLang("IDS_BORDER_CENTER", "内部竖框线");
	extfun.setResLang("IDS_BORDER_EMPTY", "无框线");
	extfun.setResLang("IDS_BORDER_RIGHT", "右框线");
	extfun.setResLang("IDS_BORDER_ALL", "所有框线");
	extfun.setResLang("IDS_BORDER_OUTSIDE", "外侧框线");
	extfun.setResLang("IDS_BORDER_INSIDE", "内部框线");
	extfun.setResLang("IDS_BORDER_USER", "自定义");
	extfun.setResLang("ID_TITLEBAR_THUMBNAIL_TITLE", "缩略图");
	extfun.setResLang("ID_TITLEBAR_TREE_TITLE", "Tree");
	extfun.setResLang("IDS_SEAL_DESCRIPTION", "Please align the seal recognition area with the green guidelines.");
	extfun.setResLang("IDS_DIALOG_FORMAT", "格式");
	extfun.setResLang("IDS_ATTACHMENTS_COUNT", "Files attached");
	extfun.setResLang("IDS_ATTACHMENTS_APPEND", "Add");
	extfun.setResLang("IDS_ATTACHMENTS_DOWNLOAD", "Download");
	extfun.setResLang("IDS_ATTACHMENTS_DELETE", "Delete");
	extfun.setResLang("IDS_ATTACHMENTS_EMPTY", "Drag and drop a file here\nOR\nClick \"Add\" button.");
	extfun.setResLang("IDS_ATTACHMENTS_MAXSIZE", "Max size is n MB");
	extfun.setResLang("IDS_ATTACHMENTS_IMAGE_INDIVIDUALLY", "Attach individually");
	extfun.setResLang("IDS_ATTACHERROR_UNSUPPORTED", "Unsupported file format");
	extfun.setResLang("IDS_ATTACHERROR_OVERSIZE", "Max size exceeded");
	extfun.setResLang("IDS_ATTACHERROR_INVALID_PDF", "Unknown PDF file");
	extfun.setResLang("IDS_ATTACHERROR_PASSWORD_PDF", "Password protected PDF file");
	extfun.setResLang("IDS_SEAL_IMAGE_UPLOAD", "도장 이미지 업로드");
	extfun.setResLang("IDS_SEAL_IMAGE_REUPLOAD", "도장 이미지 다시 업로드");
	extfun.setResLang("IDS_SEAL_IMAGE_APPLY", "적용하기");
	extfun.setResLang("IDS_SCAN_SUCCESS", "도장 이미지 인식에 성공하였습니다. ");
	extfun.setResLang("IDS_SCAN_FAIL", "도장 이미지를 인식할 수 없습니다. ");
	extfun.setResLang("IDS_SCAN_RETRY", "다시 인식하시려면 다시 스캔 해주세요.");
	extfun.setResLang("IDS_SCAN_REUPLOAD", "다시 선택하시려면 이미지를 다시 업로드 해주세요.");
	extfun.setResLang("IDS_SCAN_RETRY_LINK", "다시 스캔");
	extfun.setResLang("IDS_SCAN_REUPLOAD_LINK", "다시 업로드");
	extfun.setResLang("IDS_SCAN_UPLOAD_FAIL", "이미지를 다시 업로드 해주세요.");
	extfun.setResLang("IDS_MSG_SCAN_WAITING", "이미지를 분석 중입니다. 잠시만 기다려주세요.");
	extfun.setResLang("IDS_OPT_FONT_STYLE", "字形");
	extfun.setResLang("IDS_OPT_COLOR", "顏色");
	extfun.setResLang("IDS_REMOVE_MEMO", "是否刪除?");
	extfun.setResLang("IDS_OPT_MEMO", "Memo");
	extfun.setResLang("IDS_OZVS_ERROR_PLAY", "The video signature cannot be executed.");
	extfun.setResLang("IDS_OZVR_RECORD_COMPLETED", "Recording has been completed.");
	extfun.setResLang("IDS_OZVR_ERROR_PLAY", "播放失敗");
}