with (__oznamespace__) {
	extfun.setResLang("IDS_GANTT_YEAR", "年");
	extfun.setResLang("IDS_GANTT_QUARTER", "四半期");
	extfun.setResLang("IDS_GANTT_MONTH", "月");
	extfun.setResLang("IDS_GANTT_DAY", "日");
	extfun.setResLang("IDS_BMT_START_DATA", "データ照会開始時間：");
	extfun.setResLang("IDS_BMT_END_DATA", "データ照会完了時間：");
	extfun.setResLang("IDS_BMT_START_BIND", "バインド開始時間：");
	extfun.setResLang("IDS_BMT_END_BIND", "バインド完了時間：");
	extfun.setResLang("IDS_BMT_START_LOAD", "テンプレート生成開始時間：");
	extfun.setResLang("IDS_BMT_END_LOAD", "テンプレート生成完了時間：");
	extfun.setResLang("IDS_BMT_START_EXPORT", "エクスポート開始時間：");
	extfun.setResLang("IDS_BMT_END_EXPORT", "エクスポート完了時間：");
	extfun.setResLang("IDS_MSG_ABOUT_FORCS", "\n注意：本ソフトウェアは著作法と国際協約の保護を受けます。\n\n本ソフトウェアを全部または一部を無断で複製、配布する行為は民事および\n刑事法によって厳格に規制され、起訴の事由になります。");
	extfun.setResLang("IDS_MSG_LOADER_CREATE_TEMPLATE", "レポート テンプレートを生成しています。");
	extfun.setResLang("IDS_MSG_LOADER_PREPARE_CONNECTION", "サーバーへの接続を準備しています。");
	extfun.setResLang("IDS_MSG_LOADER_CONNECTED", "サーバーと正常的に接続されました。");
	extfun.setResLang("IDS_MSG_LOADER_READ_REPORT_BYTE_FROM_REMOTE", "サーバーからレポート フォームをダウンロードしています。");
	extfun.setResLang("IDS_MSG_LOADER_READ_DATA_FROM_REMOTE", "サーバーからデータをダウンロードしています。");
	extfun.setResLang("IDS_MSG_LOADER_LAUNCH_MODE", "レポート テンプレート生成情報");
	extfun.setResLang("IDS_MSG_LOADER_GENERATE_REPORT", "レポートを生成しています。");
	extfun.setResLang("IDS_MSG_MAIN_READY", "準備");
	extfun.setResLang("IDS_MSG_OZZ_OPEN", "OZDファイルを開いています。");
	extfun.setResLang("IDS_MSG_MAIN_BINDING", "レポートを生成しています。");
	extfun.setResLang("IDS_MSG_MAIN_MSG", "メッセージ");
	extfun.setResLang("IDS_ERR_LOADER_CANNOT_DECRYPT", "暗号化モジュールが一致していないため、ファイルを開けません。");
	extfun.setResLang("IDS_ERR_TITLE_PARAMETER", "パラメーター");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_RGB", "このパラメーター値は誤ったRGB値です。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_ZOOM", "誤ったZOOM値がパラメーターで使用されました。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_CHILDCOUNT", "入力された下位レポート数の指定が誤りました。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_REFRESH", "レポートの更新周期入力値が有効ではありません。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_RANGE", "PDF保存範囲が有効ではありません。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_COPIES", "誤った印刷出力枚数です。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_PAGESINONE", "割付けで出力できるページ当たり枚数が有効ではありません。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_PRINT_SPOOL_PAGES", "プリント スプール値が有効ではありません。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEWIDTH", "誤ったウィンドウの横サイズが指定されました。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEHEIGHT", "誤ったウィンドウの縦サイズが指定されました。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEX", "誤ったウィンドウのX座標が指定されました。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_FRAMEY", "誤ったウィンドウのY座標が指定されました。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_ICON_SIZE", "指定されたアイコンのサイズ パラメーター値が有効ではありません。");
	extfun.setResLang("IDS_ERR_PARAM_NOT_INT", "パラメーター値を数字型で変換することができません。");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_LINES", "誤ったページ間の行数です。");
	extfun.setResLang("IDS_ERR_DLL_LOAD_FAILED", "SWFライブラリのロードに失敗しました。\nプログラムが正常的に作動しない恐れがあります。");
	extfun.setResLang("IDS_ERR_LOADER_SERVER_NO_MSG", "リソースにメッセージ コードが存在しません。");
	extfun.setResLang("IDS_ERROR_SEARCH_CAN_NOT_FIND", "見つかることができません。");
	extfun.setResLang("IDS_FORBIDDEN_CHRS", ",./?_");
	extfun.setResLang("IDS_TEXT_ENCODING_ANSI", "ANSI");
	extfun.setResLang("IDS_TEXT_ENCODING_UNICODE", "UNICODE");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_BASELINE_DATETIME", "誤った形式のserver_baseline_datetimeパラメーター値が使用されました.");
	extfun.setResLang("IDS_NOTIFICAION_MESSAGEBOX", "お知らせ");
	extfun.setResLang("IDS_NOTIFICAION_NODATA", "照会されたデータがありません。");
	extfun.setResLang("IDS_OKSTRING", "OK");
	extfun.setResLang("IDS_CANCELSTRING", "キャンセル");
	extfun.setResLang("IDS_YESSTRING", "はい");
	extfun.setResLang("IDS_NOSTRING", "いいえ");
	extfun.setResLang("IDS_MSG_END_MAKETEMPLATE", "");
	extfun.setResLang("IDS_MSG_ENDCHECKCONOPT", "接続オプションのチェック完了");
	extfun.setResLang("IDS_MSG_MAKETEMPLATE", "レポートを生成しています。");
	extfun.setResLang("IDS_MSG_STARTRCVFORM", "レポート フォームのロード開始");
	extfun.setResLang("IDS_MSG_STARTRCVDATA", "データ モジュールのロード開始");
	extfun.setResLang("IDS_MSG_STARTBINDING", "レポートのバインド開始");
	extfun.setResLang("IDS_MSG_ENDRCVFORM", "レポート フォームの読み込み完了");
	extfun.setResLang("IDS_MSG_ENDRCVDATA", "データ モジュールの読み込み完了");
	extfun.setResLang("IDS_MSG_STARTCHECKCONOPT", "接続オプションのチェック開始");
	extfun.setResLang("IDS_STATIC_PROGRESSBAR_OZ", "OZ Report Viewer を実行しています。");
	extfun.setResLang("IDS_MSG_START_DIRECT", "プレビューをしないで印刷またはエクスポートを準備しています。");
	extfun.setResLang("IDS_MSG_IMAGEEXPORT_ERR", "処理ができる最大サイズを超えました。");
	extfun.setResLang("IDS_JAPAN_HALF1", "");
	extfun.setResLang("IDS_JAPAN_HALF2", "");
	extfun.setResLang("IDS_JAPAN_FULL1", "");
	extfun.setResLang("IDS_JAPAN_FULL2", "");
	extfun.setResLang("IDS_ERR_PARAM_INVALID_QUALITY", "誤った品質値がパラメーターで使用されました。");
	extfun.setResLang("ID_PAGE_LEFTMOST", "次のページに移動(横)");
	extfun.setResLang("ID_PAGE_LEFT", "前のページに移動(横)");
	extfun.setResLang("ID_PAGE_RIGHT", "次のページに移動(横)");
	extfun.setResLang("ID_PAGE_RIGHTMOST", "最後ページに移動(横)");
	extfun.setResLang("ID_ZOOM_RESET", "元のサイズ");
	extfun.setResLang("ID_ZOOM_IN", "拡大");
	extfun.setResLang("ID_ZOOM_OUT", "縮小");
	extfun.setResLang("ID_PAGE_CONTROL", "ページ選択");
	extfun.setResLang("ID_PAGE_TOP", "最初のページに移動(縦)");
	extfun.setResLang("ID_PAGE_UP", "前のページに移動(縦)");
	extfun.setResLang("ID_PAGE_DOWN", "次のページに移動(縦)");
	extfun.setResLang("ID_PAGE_BOTTOM", "最後ページに移動(縦)");
	extfun.setResLang("ID_FILE_ETCSAVE", "保存");
	extfun.setResLang("ID_OPT_HCDATA", "データ保存");
	extfun.setResLang("ID_OPT_BRAILLE", "Save electronic braille");
	extfun.setResLang("ID_ZOOM_IN_OUT", "拡大/縮小比率");
	extfun.setResLang("ID_OZZ_OPEN", "開く");
	extfun.setResLang("ID_FILE_CLOSE", "現在開いている文書を閉じます。\n閉じる");
	extfun.setResLang("ID_FILE_PRINT", "現在開いている文書を印刷します。\n印刷");
	extfun.setResLang("ID_APP_ABOUT", "製品情報...");
	extfun.setResLang("ID_APP_EXIT", "プログラム終了");
	extfun.setResLang("ID_PAGE", "");
	extfun.setResLang("ID_PAGE_PREVIOUS", "前のページに移動");
	extfun.setResLang("ID_REPORT_PRINT", "印刷");
	extfun.setResLang("ID_VIEWER_HELP", "ヘルプ");
	extfun.setResLang("ID_VIEWER_EXIT", "終了");
	extfun.setResLang("ID_BANKBOOK_PRINT", "通帳プリンタ印刷");
	extfun.setResLang("ID_ETC", "その他");
	extfun.setResLang("ID_EXPORT_PDF", "PDF保存");
	extfun.setResLang("ID_EXPORT_XLS", "XLS保存");
	extfun.setResLang("ID_EXPORT_DOC", "DOC保存");
	extfun.setResLang("ID_EXPORT_DOCX", "DOCX保存");
	extfun.setResLang("ID_EXPORT_OZD", "OZD保存");
	extfun.setResLang("ID_EXPORT_HTML", "HTML保存");
	extfun.setResLang("ID_EXPORT_PPT", "PPT保存");
	extfun.setResLang("ID_EXPORT_SVG", "SVG保存");
	extfun.setResLang("ID_EXPORT_TXT", "TXT保存");
	extfun.setResLang("ID_EXPORT_CSV", "CSV保存");
	extfun.setResLang("ID_EXPORT_TIF", "TIF保存");
	extfun.setResLang("ID_EXPORT_JPG", "JPG保存");
	extfun.setResLang("ID_EXPORT_HML", "HWP保存");
	extfun.setResLang("ID_EXPORT_HML97", "HML97保存");
	extfun.setResLang("ID_EXPORT_HWPX", "HWPX保存");
	extfun.setResLang("ID_EXPORT_ODT", "ODT保存");
	extfun.setResLang("ID_EXPORT_MAIL", "MAIL保存");
	extfun.setResLang("ID_SEARCH_PARAM", "照会");
	extfun.setResLang("ID_EXPORT_MHT", "MHT保存");
	extfun.setResLang("ID_EXPORT_PNG", "PNG保存");
	extfun.setResLang("ID_EXPORT_GIF", "GIF保存");
	extfun.setResLang("ID_ZOOM_SINGLEPAGE_FITTOFRAME", "画面サイズに合わせて単一ページ");
	extfun.setResLang("ID_ZOOM_SINGLEPAGECONTINUOUS_FITTOWIDTH", "幅に合わせて連続単一ページ");
	extfun.setResLang("ID_EXPORT_NXL", "NXL保存");
	extfun.setResLang("ID_EXPORT_CELL", "CELL保存");
	extfun.setResLang("ID_OPT_REFRESH", "更新");
	extfun.setResLang("ID_OPT_LABEL", "メモ追加");
	extfun.setResLang("ID_OPT_IMAGE", "Add image");
	extfun.setResLang("ID_OPT_LINE", "直線の保存");
	extfun.setResLang("ID_OPT_ARROW", "矢印の保存");
	extfun.setResLang("ID_OPT_RECTANGLE", "長方形の保存");
	extfun.setResLang("ID_OPT_CIRCLE", "楕円の保存");
	extfun.setResLang("ID_OPT_CHECKMARK", "Add checkmark");
	extfun.setResLang("ID_PAGE_PREVIOUSMOST", "最初のページに移動");
	extfun.setResLang("ID_PAGE_CURRENTPAGE", "");
	extfun.setResLang("ID_PAGE_TOTALPAGE", "");
	extfun.setResLang("ID_PAGE_NEXT", "次のページに移動");
	extfun.setResLang("ID_PAGE_NEXTMOST", "最後のページに移動");
	extfun.setResLang("ID_ZOOM_INVERSEPAPER", "用紙方向転換");
	extfun.setResLang("ID_REPORT_CLOSE", "閉じる");
	extfun.setResLang("ID_REPORT_CLOSEALL", "すべて閉じる");
	extfun.setResLang("ID_OPT_PARAMETERS", "パラメーターの入力");
	extfun.setResLang("ID_OPT_SEARCH", "検索...");
	extfun.setResLang("ID_VIEW_PAGESETUP", "ページ設定");
	extfun.setResLang("ID_VIEW_REPORT_EXPLORER", "レポート ツリー");
	extfun.setResLang("ID_CLOSE_REPORT_EXPLORER", "Close the tree");	
	extfun.setResLang("ID_VIEW_REPORT_THUMBNAIL", "ページのサムネール表示");
	extfun.setResLang("ID_CLOSE_REPORT_THUMBNAIL", "Close the thumbnail");
	extfun.setResLang("ID_EXPORT_XLSX", "XLSX保存");
	extfun.setResLang("IDS_MSG_PRINT_JOB_SUCCESS", "正常的に出力されました。");
	extfun.setResLang("IDS_MESSAGE_COPY_CLIPBOARD", "クリップボードにコピーされました。");
	extfun.setResLang("ID_VIEW_NORMAL", "実際サイズ");
	extfun.setResLang("ID_VIEW_FITTOFRAME", "画面サイズに合わせ");
	extfun.setResLang("ID_VIEW_FITTOWIDTH", "幅に合わせ");
	extfun.setResLang("ID_VIEW_FITTOCONTENTS", "表示内容に合わせ");
	extfun.setResLang("ID_VIEW_PRINTSIZE", "印刷サイズ");
	extfun.setResLang("ID_VIEW_SINGLE_PAGE", "単一ページ");
	extfun.setResLang("ID_VIEW_SINGLE_PAGE_CONTINUOUS", "連続単一ページ");
	extfun.setResLang("ID_VIEW_DOUBLE_PAGE", "二ページ表示");
	extfun.setResLang("ID_VIEW_DOUBLE_PAGE_CONTINUOUS", "連続二ページ表示");
	extfun.setResLang("ID_VIEW_CONTINUOUS", "連続ページ");
	extfun.setResLang("ID_SCREENTOOL_HAND", "手のひらツール");
	extfun.setResLang("ID_SCREENTOOL_EDIT", "編集モード");
	extfun.setResLang("ID_SCREENTOOL_TEXTSELECT", "テキスト選択モード");
	extfun.setResLang("ID_SCREENTOOL_MULTISCREENGUIDE", "案内モード");
	extfun.setResLang("ID_MENU_SAVEASIMAGE", "名前を付けてイメージを保存...");
	extfun.setResLang("ID_MENU_SAVEASAUDIO", "名前を付けて録音データを保存...");
	extfun.setResLang("ID_MENU_INITIALIZEINPUTDATA", "入力データの初期化");
	extfun.setResLang("ID_MENU_DELETE", "削除");
	extfun.setResLang("ID_MENU_EDIT", "属性変更");
	extfun.setResLang("ID_MENU_DONOTPRINT", "印刷しない");
	extfun.setResLang("ID_MENU_CHANGE_LABEL", "ラベル");
	extfun.setResLang("ID_MENU_CHANGE_IMAGE", "イメージ");
	extfun.setResLang("ID_MENU_CHANGE_BARCODE", "バーコード");
	extfun.setResLang("ID_MENU_CHANGE_PDF417", "PDF417バーコード");
	extfun.setResLang("ID_MENU_CHANGE_HTML", "HTML");
	extfun.setResLang("ID_MENU_CHANGE_QRBARCODE", "QRバーコード");
	extfun.setResLang("ID_MENU_CHANGE_DATAMATRIX", "DataMatrixバーコード");
	extfun.setResLang("ID_MENU_CHARTEDIT", "回転可能");
	extfun.setResLang("IDS_MSG_COMP_EDIT", "属性編集");
	extfun.setResLang("IDS_MSG_COMP_MOVE", "移動");
	extfun.setResLang("IDS_MSG_COMP_INPUT", "入力");
	extfun.setResLang("IDS_MSG_COMP_LINK", "リンク");
	extfun.setResLang("IDS_MSG_COMP_POSSIBLE", "可能");
	extfun.setResLang("IDS_MSG_COMP_IMPOSSIBLE", "不可能");
	extfun.setResLang("IDS_MSG_COMP_NAME_RECTANGLE", "長方形");
	extfun.setResLang("IDS_MSG_COMP_NAME_ELLIPSE", "楕円");
	extfun.setResLang("IDS_MSG_COMP_NAME_LINE", "直線");
	extfun.setResLang("IDS_MSG_COMP_NAME_ARROW", "矢印");
	extfun.setResLang("IDS_MSG_COMP_NAME_CHART", "チャート");
	extfun.setResLang("IDS_MSG_COMP_NAME_MEMO_LABEL", "メモ ラベル");
	extfun.setResLang("IDS_MSG_COMP_NAME_LABEL", "ラベル");
	extfun.setResLang("IDS_MSG_COMP_NAME_BARCODE", "バーコード");
	extfun.setResLang("IDS_MSG_COMP_NAME_BARCODE2", "2次元バーコード");
	extfun.setResLang("IDS_MSG_COMP_NAME_IMAGE", "イメージ");
	extfun.setResLang("IDS_MSG_OUTPUT_INFO", "情報");
	extfun.setResLang("IDS_MSG_OUTPUT_DEBUG", "デバッグ");
	extfun.setResLang("IDS_MSG_OUTPUT_ERROR", "エラー");
	extfun.setResLang("IDS_MSG_OUTPUT_ALL", "すべて");
	extfun.setResLang("IDS_MSG_COMP_NAME_MEMO_CHECKMARK", "CheckMark");
	extfun.setResLang("IDS_OZFONT_PLAIN", "一般");
	extfun.setResLang("IDS_OZFONT_ITALIC", "斜体");
	extfun.setResLang("IDS_OZFONT_BOLD", "太字");
	extfun.setResLang("IDS_OZFONT_BOLDITALIC", "太字 斜体");
	extfun.setResLang("IDS_DYN_CENTER", "中央");
	extfun.setResLang("IDS_DYN_LEFT", "左");
	extfun.setResLang("IDS_DYN_RIGHT", "右");
	extfun.setResLang("IDS_DYN_TOP", "上");
	extfun.setResLang("IDS_DYN_BOTTOM", "下");
	extfun.setResLang("IDS_DYN_NONE", "なし");
	extfun.setResLang("IDS_DYN_IMG_NORMAL", "一般");
	extfun.setResLang("IDS_DYN_IMG_CENTER", "中央");
	extfun.setResLang("IDS_DYN_IMG_FIT", "全体に表示");
	extfun.setResLang("IDS_DYN_IMG_TILE", "並べて表示");
	extfun.setResLang("IDS_DYN_IMG_FITBYWIDTH", "横固定");
	extfun.setResLang("IDS_DYN_IMG_FITBYHEIGHT", "縦固定");
	extfun.setResLang("IDS_DYN_IMG_ISOTROPIC", "等間隔");
	extfun.setResLang("IDS_DYN_IMG_TOPCENTER", "上段横方向中央揃え");
	extfun.setResLang("IDS_DYN_IMG_TOPRIGHT", "上段右揃え");
	extfun.setResLang("IDS_DYN_IMG_MIDDLELEFT", "縦方向中央段左揃え");
	extfun.setResLang("IDS_DYN_IMG_MIDDLERIGHT", "縦方向中央段右揃え");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMLEFT", "下段左揃え");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMCENTER", "下段横方向中央揃え");
	extfun.setResLang("IDS_DYN_IMG_BOTTOMRIGHT", "下段右揃え");
	extfun.setResLang("IDS_DYN_IMG_FITBYWIDTH_CENTER", "横固定中央");
	extfun.setResLang("IDS_DYN_IMG_FITBYHEIGHT_CENTER", "縦固定中央");
	extfun.setResLang("IDS_DYN_IMG_ISOTROPIC_CENTER", "等間隔中央");
	extfun.setResLang("IDS_DYN_TRUE", "はい");
	extfun.setResLang("IDS_DYN_FALSE", "いいえ");
	extfun.setResLang("IDS_DYN_HORIZONTAL", "横");
	extfun.setResLang("IDS_DYN_VERTICAL", "縦");
	extfun.setResLang("IDS_DYN_SHAPE_SLASH", "スラッシュ");
	extfun.setResLang("IDS_DYN_SHAPE_BACKSLASH", "逆スラッシュ");
	extfun.setResLang("IDS_QRENCODING_UTF8", "UTF-8");
	extfun.setResLang("IDS_QRENCODING_ANSI", "ANSI");
	extfun.setResLang("IDS_QRECC_L", "L");
	extfun.setResLang("IDS_QRECC_M", "M");
	extfun.setResLang("IDS_QRECC_Q", "Q");
	extfun.setResLang("IDS_QRECC_H", "H");
	extfun.setResLang("IDS_VERIFYQRCODE_NOTPRINTED", "この文書は印刷物ではありません。上記の改ざん防止確認を行うには、印刷された文書のQRコードをスキャンしてください。");
	extfun.setResLang("IDS_NO_LINE_START", "!%),.:;?]}¢°’”‰′″℃、。々〉》」』】〕゛゜ゝゞ・ヽヾ！％），．：；？］｝｡｣､･ﾞﾟ￠");
	extfun.setResLang("IDS_NO_LINE_END", "$([\{£¥‘“〈《「『【〔＄（［｛｢￡￥");
	extfun.setResLang("IDS_MSG_OVERWRITE", "ファイルが既にあります。\n既存ファイルを置き換えしますか？");
	extfun.setResLang("IDS_MSG_SAVE", "保存");
	extfun.setResLang("ID_PAGE_PREVIOUS2", "前のページ");
	extfun.setResLang("ID_PAGE_NEXT2", "次のページ");
	extfun.setResLang("ID_ZOOM_RESET2", "元のサイズ");
	extfun.setResLang("ID_ZOOM_IN2", "拡大");
	extfun.setResLang("ID_ZOOM_OUT2", "縮小");
	extfun.setResLang("ID_MENU_DONOTPRINT2", "印刷する");
	extfun.setResLang("ID_MENU_CHARTEDIT2", "チャートの回転モード取り消し");
	extfun.setResLang("IDS_PRINT_RANGE_ERROR", "印刷範囲が正確ではありません。");
	extfun.setResLang("IDS_PRINT_RANGE_EMPTY", "印刷範囲を入力してください。");
	extfun.setResLang("IDS_EXCEL_RANGE_ERROR", "行範囲が正確ではありません。");
	extfun.setResLang("IDS_EXCEL_RANGE_EMPTY", "行範囲を入力してください。");
	extfun.setResLang("IDS_HTML_VERSION", "None");
	extfun.setResLang("IDC_INVALID_PASSWORD", "パスワードに許可されていない文字が指定され、暗号化せずに保存されます。");
	extfun.setResLang("ID_COMMENT_HIDE", "入力モード");
	extfun.setResLang("ID_COMMENT_PEN", "ペン");
	extfun.setResLang("ID_COMMENT_HPEN", "蛍光ペン");
	extfun.setResLang("ID_COMMENT_CLEAR", "全て削除");
	extfun.setResLang("ID_COMMENT_SIZE1", "ペンの太さ");
	extfun.setResLang("ID_COMMENT_SIZE10", "ペンの太さ");
	extfun.setResLang("ID_COMMENT_SIZE18", "ペンの太さ");
	extfun.setResLang("ID_COMMENT_PENCOLOR1", "ペンの色");
	extfun.setResLang("ID_COMMENT_PENCOLOR2", "ペンの色");
	extfun.setResLang("IC_COMMENT_COLOR3", "ペンの色");
	extfun.setResLang("ID_COMMENT_PENCOLOR3", "ペンの色");
	extfun.setResLang("ID_COMMENT_ERASERPEN", "消しゴム");
	extfun.setResLang("ID_SCREENTOOL_COMMENT", "コメントモード");
	extfun.setResLang("ID_COMMENT_PENCOLOR4", "ペンの色");
	extfun.setResLang("ID_COMMENT_PENCOLOR5", "ペンの色");
	extfun.setResLang("ID_COMMENT_PENCOLOR6", "ペンの色");
	extfun.setResLang("ID_COMMENT_DRAW_BORDER", "枠線描画");
	extfun.setResLang("ID_COMMENT_FILL_BACKGROUND", "背景色の塗りつぶし");
	extfun.setResLang("IDS_COMMENT_PEN_TITLE", "ペンの太さ & 色");
	extfun.setResLang("IDS_COMMENT_HPEN_TITLE", "蛍光ペンの太さ & 色");
	extfun.setResLang("IDS_REMOVE_COMMENT", "全てのコメントを削除しますか？");
	extfun.setResLang("IDS_COMMENT_PEN", "");
	extfun.setResLang("IDS_COMMENT_HPEN", "");
	extfun.setResLang("IDS_COMMENT_REMOVE_ALL", "");
	extfun.setResLang("IDS_COMMENT_DRAW_BORDER_TITLE", "枠線の太さ & 色");
	extfun.setResLang("IDS_COMMENT_FILL_BACKGROUND_TITLE", "背景の色");
	extfun.setResLang("ID_TEXT_COPY", "コピー");
	extfun.setResLang("ID_TEXT_SELECT_ALL", "すべて選択");
	extfun.setResLang("ID_TEXT_DESELECT_ALL", "すべて選択解除");
	extfun.setResLang("ID_START_EDITING", "入力開始");
	extfun.setResLang("ID_END_EDITING", "入力終了");
	extfun.setResLang("ID_COPYINPUTDATA_JSON", "入力データコピー (json)");
	extfun.setResLang("ID_COPYINPUTDATA_XML", "入力データコピー (xml)");
	extfun.setResLang("ID_COPY_PROCESSOR_ID", "Processor ID コピー");
	extfun.setResLang("IDS_MSG_PROGRESS_BINDING", "レポートをバインディングしています。");
	extfun.setResLang("ID_MENU_SAVETABLEASPNG", "テーブル保存(PNG)…");
	extfun.setResLang("ID_MENU_SAVETABLEASHTML", "テーブル保存(HTML)…");
	extfun.setResLang("ID_MENU_SHOW_SAVED_HISTORY", "保存履歴を見る");
	extfun.setResLang("ID_HISTORY_SAVED", "保存履歴");
	extfun.setResLang("ID_HISTORY_DETAIL", "項目別詳細履歴");
	extfun.setResLang("ID_HISTORY_BACK", "戻る");
	extfun.setResLang("ID_HISTORY_REVERT", "元に戻す");
	extfun.setResLang("ID_HISTORY_COMPLETE", "完了");
	extfun.setResLang("IDS_BMT_START_SVG_BIND", "バインド開始:");
	extfun.setResLang("IDS_BMT_SVG_BINDING", "バインド中:");
	extfun.setResLang("IDS_BMT_END_SVG_BIND", "バインド完了:");
	extfun.setResLang("IDS_MSG_LOADER_READ_PAGE_FROM_REMOTE", "サーバーからページを読み込んでいます。");
	extfun.setResLang("ID_OPT_SHOWCONSOLE", "コンソール確認...");
	extfun.setResLang("IDS_MSG_SCAN_ID_FAIL", "IDイメージを認識することができません。撮影ボタンをクリックして再撮影してください。");
	extfun.setResLang("IDS_OPT_SAVEAS_DEFAULT", "基本設定");
	extfun.setResLang("IDS_OPT_SAVEAS", "レポートを保存");
	extfun.setResLang("IDS_OPT_SAVE_WAY_TXT", "Save report after binding per one page/pages.");
	extfun.setResLang("IDS_OPT_SAVE_WAY_ONEPAGE", "Save Per OnePage");
	extfun.setResLang("IDS_OPT_SAVE_WAY_EACHPAGE", "Save Per Pages");
	extfun.setResLang("IDS_OPT_SAVE_WAY", "保存方式");
	extfun.setResLang("IDS_OPT_SAVE_ACTION", "Action");
	extfun.setResLang("IDS_OPT_SAVE_MULTIDOC", "マルチ レポート");
	extfun.setResLang("IDS_OPT_SAVE_AREA", "保存ページの範囲");
	extfun.setResLang("IDS_OPT_SAVE_COMPONENT", "コンポーネント");
	extfun.setResLang("IDS_OPT_SAVE_LINK_INFO", "リンク情報の保存");
	extfun.setResLang("IDS_OPT_ACTION_AFTER_SAVE", "Action after save");
	extfun.setResLang("IDS_OPT_SAVE_ONEFILE", "１つのファイルで保存");
	extfun.setResLang("IDS_OPT_SAVE_ALLFILE", "全てのレポートを保存");
	extfun.setResLang("IDS_OPT_ALLPAGE", "すべて");
	extfun.setResLang("IDS_OPT_CURRENTPAGE", "現在のページ");
	extfun.setResLang("IDS_OPT_SELECTEDPAGE", "選択したページ");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE", "ページ指定 : ");
	extfun.setResLang("IDS_OPT_COMPONENT_LABEL", "保存するコンポーネントをチェックしてください");
	extfun.setResLang("IDS_OPT_LABEL", "ラベル");
	extfun.setResLang("IDS_OPT_IMAGE", "イメージ");
	extfun.setResLang("IDS_OPT_BARCODE", "バーコード");
	extfun.setResLang("IDS_OPT_PDF417", "PDF417コード");
	extfun.setResLang("IDS_OPT_QR_BARCODE", "QRコード");
	extfun.setResLang("IDS_OPT_HTML", "HTML");
	extfun.setResLang("IDS_OPT_CHART", "チャート");
	extfun.setResLang("IDS_OPT_LINE", "直線");
	extfun.setResLang("IDS_OPT_CIRCLE", "楕円");
	extfun.setResLang("IDS_OPT_RECTANGLE", "長方形");
	extfun.setResLang("IDS_OPT_ARROW", "矢印");
	extfun.setResLang("IDS_OPT_URL_LINK", "URLリンク");
	extfun.setResLang("IDS_OPT_LIST_LINK", "目次リンク");
	extfun.setResLang("IDS_OPT_PDF_SAVE", "PDF保存の設定");
	extfun.setResLang("IDS_OPT_DOC_IMFOR", "文書情報");
	extfun.setResLang("IDS_OPT_OPEN_PROTECT", "読み取りパスワード");
	extfun.setResLang("IDS_OPT_EDIT_PROTECT", "書き込みパスワード");
	extfun.setResLang("IDS_OPT_USER_RIGHT", "ユーザーのアクセス権限");
	extfun.setResLang("IDS_OPT_TITLE", "タイトル");
	extfun.setResLang("IDS_OPT_WRITER", "作成者");
	extfun.setResLang("IDS_OPT_SUBJECT", "サブ タイトル");
	extfun.setResLang("IDS_OPT_KEYWORD", "キーワード");
	extfun.setResLang("IDS_OPT_APPLICATION", "アプリケーション");
	extfun.setResLang("IDS_OPT_USER_PW", "パスワード");
	extfun.setResLang("IDS_OPT_USER_PW_CONFIRM", "パスワードの確認");
	extfun.setResLang("IDS_OPT_MASTER_PW", "パスワード");
	extfun.setResLang("IDS_OPT_MASTER_PW_CONFIRM", "パスワードの確認");
	extfun.setResLang("IDS_OPT_PRINT_PERMIT", "印刷可能");
	extfun.setResLang("IDS_OPT_CONTENTS_COPY", "内容のコピー");
	extfun.setResLang("IDS_OPT_SAVEIMG_TOCHART", "チャートをイメージで保存");
	extfun.setResLang("IDS_OPT_FONT_INCLUDE", "폰트 포함");
	extfun.setResLang("IDS_OPT_PRINT", "印刷");
	extfun.setResLang("IDS_OPT_PRINT_COUNT", "印刷枚数");
	extfun.setResLang("IDS_OPT_PRINT_SCOPE", "印刷範囲");
	extfun.setResLang("IDS_OPT_PRINT_RULE", "印刷方式");
	extfun.setResLang("IDS_OPT_COUNT", "枚");
	extfun.setResLang("IDS_OPT_PRINT_ONEPAGE", "一部ずつ印刷");
	extfun.setResLang("IDS_OPT_PRINT_ALL_REPORT", "すべての文書を印刷");
	extfun.setResLang("IDS_OPT_ALL", "すべて");
	extfun.setResLang("IDS_OPT_CHOOSE_PAGE", "ページ指定");
	extfun.setResLang("IDS_OPT_PRINT_FITTOPAGE", "用紙にあわせて印刷");
	extfun.setResLang("IDS_OPT_DEVIDE_PRINT", "分割印刷");
	extfun.setResLang("IDS_OPT_DEVIDE_PRINT_TOFITPAPER", "用紙に合わせて分割印刷");
	extfun.setResLang("IDS_TOGETHER_PRINT", "割付け印刷");
	extfun.setResLang("IDS_OPT_PAGECOUNT_TOPRINT", "割付けページ数");
	extfun.setResLang("IDS_OPT_PRINT_ORDER", "印刷順序");
	extfun.setResLang("IDS_OPT_HORIZON", "左右");
	extfun.setResLang("IDS_OPT_VERTICAL", "上下");
	extfun.setResLang("IDS_OPT_PRINT_DIRECTION", "印刷方向");
	extfun.setResLang("IDS_OPT_PORTRAIT", "縦");
	extfun.setResLang("IDS_OPT_LANDSCAPE", "横");
	extfun.setResLang("IDS_OPT_OPTION", "設定");
	extfun.setResLang("IDS_OPT_CONFIRM", "OK");
	extfun.setResLang("IDS_OPT_CANCEL", "キャンセル");
	extfun.setResLang("IDS_OPT_CLOSE", "閉じる");
	extfun.setResLang("IDS_OPT_SAVE", "저장");
	extfun.setResLang("IDS_OPT_OZD_SAVE_OPTION", "OZD保存の設定");
	extfun.setResLang("IDS_OPT_PASSWORD", "パスワード");
	extfun.setResLang("IDS_OPT_MEMOADD_OK", "編集内容を含む");
	extfun.setResLang("IDS_OPT_SAVE_ALLREPORT", "複数レポートの保存");
	extfun.setResLang("IDS_OPT_INCLUDE_IMG", "イメージを含む");
	extfun.setResLang("IDS_OPT_FILE_TYPE", "ファイルの種類");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE", "Excel保存の設定");
	extfun.setResLang("IDS_OPT_WORD_SAVE", "Word保存の設定");
	extfun.setResLang("IDS_OPT_DOCX_SAVE", "Word保存の設定");
	extfun.setResLang("IDS_OPT_PPT_SAVE", "PowerPoint保存の設定");
	extfun.setResLang("IDS_OPT_HTML_SAVE", "HTML保存の設定");
	extfun.setResLang("IDS_OPT_CSV_SAVE", "CSV保存の設定");
	extfun.setResLang("IDS_OPT_TEXT_SAVE", "TEXT保存の設定");
	extfun.setResLang("IDS_OPT_JPG_SAVE", "JPG保存の設定");
	extfun.setResLang("IDS_OPT_TIFF_SAVE", "TIFF保存の設定");
	extfun.setResLang("IDS_OPT_HWP_SAVE", "HWP保存の設定");
	extfun.setResLang("IDS_OPT_HWP97_SAVE", "HWP97保存の設定");
	extfun.setResLang("IDS_OPT_MHT_SAVE", "MHT保存の設定");
	extfun.setResLang("IDS_OPT_SAVE_FORM", "保存形式");
	extfun.setResLang("IDS_OPT_PAGE", "ページ");
	extfun.setResLang("IDS_OPT_FONT", "フォント");
	extfun.setResLang("IDS_OPT_FORMAT", "書式");
	extfun.setResLang("IDS_OPT_AUTO_FIT", "次のページ数に合わせる");
	extfun.setResLang("IDS_OPT_CELL_MINIMUM_SIZE_CELL", "セルの最小サイズ");
	extfun.setResLang("IDS_OPT_SAVE_MODE", "保存形式");
	extfun.setResLang("IDS_OPT_KEEP_FORM_ATTR", "レポートタイプの保持");
	extfun.setResLang("IDS_OPT_IGNORE_COLOR_OUTLINE_CELL", "色、枠線、セル結合の無視");
	extfun.setResLang("IDS_OPT_REMOVE_CELL_AFTERDIVIDE", "分割後空白セルを削除");
	extfun.setResLang("IDS_OPT_SAVE_SHEET_PER_COLPAGE", "ページの列ごとにシートに保存");
	extfun.setResLang("IDS_OPT_SAVE_SHEET_PAGE", "ページごとにシートに保存");
	extfun.setResLang("IDS_OPT_COLUMN_FIRST", "列を優先して保存");
	extfun.setResLang("IDS_OPT_ROW_FIRST", "行を優先して保存");
	extfun.setResLang("IDS_OPT_REMOVE_PAGE_GAP", "ページ間の空白の削除");
	extfun.setResLang("IDS_OPT_SIZE_COLON", "サイズ:");
	extfun.setResLang("IDS_OPT_REMOVE_LINE", "行の削除");
	extfun.setResLang("IDS_OPT_EXCLUDE_FIRST_PAGE", "先頭ページ除外");
	extfun.setResLang("IDS_OPT_ONLY_FIRST_PAGE", "先頭ページのみ");
	extfun.setResLang("IDS_OPT_ALL_PAGE", "すべて");
	extfun.setResLang("IDS_OPT_LINE_SCOPE_LINE_NUMBER", "行の範囲を(-)で、行番号をカンマ(,)またはスラッシュ(/)で区切って指定してください。例）1-3,5,12");
	extfun.setResLang("IDS_OPT_CHANGE_TXT_TO_INTEGER", "数値を数字に変換");
	extfun.setResLang("IDS_OPT_APPLY_ONLYLABEL_NUMBER", "表示形式が数字のラベルのみ適用");
	extfun.setResLang("IDC_CHECK_APPLY_DATETIMEFORMAT", "Date type text convert to date");
	extfun.setResLang("IDS_OPT_CHANGE_AS_NORMAL", "セルの書式設定を標準に変換");
	extfun.setResLang("IDS_OPT_FONT_COLON", "フォント:");
	extfun.setResLang("IDS_OPT_WIDTH", "幅");
	extfun.setResLang("IDS_OPT_HEIGHT", "高さ");
	extfun.setResLang("IDS_OPT_SAVE_MHT_TYPE", "mht形式で保存 （Office XP以降対応）");
	extfun.setResLang("IDS_OPT_TABLE_SAVE_WAY", "テーブルの保存方式");
	extfun.setResLang("IDS_OPT_TABLE_TYPE_WAY", "テーブル形式で保存           ");
	extfun.setResLang("IDS_OPT_BAND_SAVE_WAY", "バンド保存方式");
	extfun.setResLang("IDS_OPT_BAND_SAVE_PAGE", "ページ ヘッダー/フッター バンドをヘッダー/フッターに保存");
	extfun.setResLang("IDS_OPT_PPT_SAVE_WAY", "PowerPoint保存方式");
	extfun.setResLang("IDS_OPT_MHTD_SAVE_PAGE", "mht形式で保存（Office XP以降対応）");
	extfun.setResLang("IDS_OPT_FONT_SIZE_SETTING", "フォント サイズ");
	extfun.setResLang("IDS_OPT_PAGE_BETWEEN", "ページの間隔");
	extfun.setResLang("IDS_OPT_PER_PAGE_SAVE", "ページごとに保存");
	extfun.setResLang("IDS_OPT_LINE_COUNT_COLON", "ページ間の余白(ピクセル)");
	extfun.setResLang("IDS_OPT_OFFSET_COLON", "オフセット :");
	extfun.setResLang("IDS_OPT_STARTPOINT_HTMLDOC", "HTML開始座標");
	extfun.setResLang("IDS_OPT_ENCODING_COLON", "エンコード方式 :");
	extfun.setResLang("IDS_OPT_X_AXIS", "X軸");
	extfun.setResLang("IDS_OPT_Y_AXIS", "Y軸");
	extfun.setResLang("IDS_OPT_OFFSET", "オフセット");
	extfun.setResLang("IDS_OPT_SEPARATION", "文字の区切り");
	extfun.setResLang("IDS_OPT_SEPARATOR", "区切り文字");
	extfun.setResLang("IDS_OPT_USER_DEFINE", "ユーザー定義");
	extfun.setResLang("IDS_OPT_SEPARATION_TYPE", "区切り形式");
	extfun.setResLang("IDS_OPT_PAGE_BRACKET", "<PAGE>");
	extfun.setResLang("IDS_OPT_SET_PAGELINE", "ページ間の行数");
	extfun.setResLang("IDS_OPT_CHAR_NUMBER", "数字");
	extfun.setResLang("IDS_OPT_ADD_SEPARATOR", "桁数の区切り文字を追加");
	extfun.setResLang("IDS_OPT_REMOVE_SEPARATOR", "桁数の区切り文字を削除");
	extfun.setResLang("IDS_OPT_PAGE_SEPARATION", "ページの区切り");
	extfun.setResLang("IDS_OPT_LABEL_SAVE", "ラベルの保存方式");
	extfun.setResLang("IDS_OPT_LABEL_SIZE", "ラベルサイズ固定");
	extfun.setResLang("IDS_OPT_POSITION_SAVE", "位置の保存方式");
	extfun.setResLang("IDS_OPT_VERTREL_TOPARA", "縦を文段に設定");
	extfun.setResLang("IDS_OPT_BACKGROUND_BAND", "バックグラウンドバンドをグラウンド側に保存");
	extfun.setResLang("IDS_OPT_TITLE_COLON", "タイトル  :");
	extfun.setResLang("IDS_OPT_DISPLAY_OPTION", "表示オプション");
	extfun.setResLang("IDS_OPT_GRIDLINES", "枠線を表示する");
	extfun.setResLang("IDS_OPT_ENCODING_WAY", "エンコード方式");
	extfun.setResLang("IDS_OPT_ENCODING_G3", "G3");
	extfun.setResLang("IDS_OPT_ENCODING_G4", "G4");
	extfun.setResLang("IDS_OPT_ENCODING_SAVEAS_ONEFILE", "１つのファイルに保存");
	extfun.setResLang("IDS_OPT_RATIO", "比率");
	extfun.setResLang("IDS_OPT_ZOOM_INOUT", "拡大/縮小比率");
	extfun.setResLang("IDS_OPT_SET_DPI", "解像度によってサイズ決定");
	extfun.setResLang("IDS_OPT_DPI", "DPI");
	extfun.setResLang("IDS_OPT_SIZE", "サイズ");
	extfun.setResLang("IDS_OPT_SAVE_RATIO", "保存倍率");
	extfun.setResLang("IDS_OPT_COMPRESSION", "圧縮");
	extfun.setResLang("IDS_OPT_QUALITY", "品質");
	extfun.setResLang("IDS_OPT_USE_INDENT", "インデント");
	extfun.setResLang("IDS_OPT_DATA_SAVE", "データ保存");
	extfun.setResLang("IDS_OPT_FIND_WHAT", "検索する内容：");
	extfun.setResLang("IDS_OPT_MATCH_WHOLE_WORD", "単語単位で探す");
	extfun.setResLang("IDS_OPT_MATCH_CASE", "大文字と小文字を区別する");
	extfun.setResLang("IDS_OPT_DIRECTION", "方向");
	extfun.setResLang("IDS_OPT_SEARCH_UP", "上へ");
	extfun.setResLang("IDS_OPT_SEARCH_DOWN", "下へ");
	extfun.setResLang("IDS_OPT_NEXT", "次を検索");
	extfun.setResLang("IDS_OPT_REFRESH_REPORT", "更新");
	extfun.setResLang("IDS_OPT_INTERVAL", "周期");
	extfun.setResLang("IDS_OPT_HH", "時");
	extfun.setResLang("IDS_OPT_MM", "分");
	extfun.setResLang("IDS_OPT_SS", "秒");
	extfun.setResLang("IDS_OPT_REFRESH_NOW", "更新");
	extfun.setResLang("IDS_OPT_START", "開始");
	extfun.setResLang("IDS_OPT_STOP", "終了");
	extfun.setResLang("IDS_OPT_LEFT_COLON", "左:");
	extfun.setResLang("IDS_OPT_RIGHT_COLON", "右:");
	extfun.setResLang("IDS_OPT_TOP_COLON", "上:");
	extfun.setResLang("IDS_OPT_BOTTOM_COLON", "下:");
	extfun.setResLang("IDS_OPT_PAGE_SETUP", "ページ設定");
	extfun.setResLang("IDS_OPT_MARGIN", "余白");
	extfun.setResLang("IDS_OPT_UNIT", "使用単位");
	extfun.setResLang("IDS_OPT_UNIT_COLON", "単位：");
	extfun.setResLang("IDS_OPT_MARGIN_OPTION", "余白オプション");
	extfun.setResLang("IDS_OPT_MARGIN_DEFAULT", "基本余白使用");
	extfun.setResLang("IDS_OPT_MARGIN_AUTO_ADJUST", "自動調整");
	extfun.setResLang("IDS_OPT_HTML_VERSION", "バージョン");
	extfun.setResLang("IDS_OPT_HTML_VERSION_COLON", "HTML バージョン :");
	extfun.setResLang("IDS_OPT_TOTAL", "全体");
	extfun.setResLang("IDS_OPT_REPORT_STRUCTURE", "レポートの構造表示");
	extfun.setResLang("IDS_OPT_LABEL_FORMAT", "ラベル書式");
	extfun.setResLang("IDS_OPT_PARAGRAPH", "段落");
	extfun.setResLang("IDS_OPT_FILL", "塗りつぶし");
	extfun.setResLang("IDS_OPT_LINECOLOR", "枠線");
	extfun.setResLang("IDS_OPT_ETC", "その他");
	extfun.setResLang("IDS_OPT_ALIGNMENT", "文字の配置");
	extfun.setResLang("IDS_OPT_TXT_DIRECTION", "テキスト方向");
	extfun.setResLang("IDS_OPT_INTERNAL_MARGIN", "内部余白");
	extfun.setResLang("IDS_OPT_PREVIEW", "プレビュー");
	extfun.setResLang("IDS_OPT_HORIZON_COLON", "左右：");
	extfun.setResLang("IDS_OPT_VERTICAL_COLON", "上下：");
	extfun.setResLang("IDS_OPT_LINE_SPACE_COLON", "行間：");
	extfun.setResLang("IDS_OPT_INDENT_COLON", "インデント：");
	extfun.setResLang("ID_OPT_PARAMETERS_TITLE_LABEL", "パラメーター値を修正します。");
	extfun.setResLang("IDS_OPT_EXIT", "終了");
	extfun.setResLang("IDS_OPT_OZZPASSWORD", "パスワード");
	extfun.setResLang("IDS_OPT_OZZPASSWORD_CHECK", "パスワード確認");
	extfun.setResLang("IDS_OPT_ID", "ID");
	extfun.setResLang("IDS_OPT_SECURITY", "セキュレティー");
	extfun.setResLang("IDS_OPT_PRODUCT_INFO", "製品情報");
	extfun.setResLang("IDS_OPT_OZ_INFO", "製品 情報");
	extfun.setResLang("IDS_OPT_ERROR_CODE_COLON", "エラー コード:");
	extfun.setResLang("IDS_OPT_GENERAL_MSG_COLON", "一般メッセージ：");
	extfun.setResLang("IDS_OPT_VIEW_DETAIL", "詳細プレビュー");
	extfun.setResLang("IDS_OPT_DETAIL_MSG_COLON", "詳細メッセージ：");
	extfun.setResLang("IDS_OPT_TEXT_CONTROL", "文字の制御");
	extfun.setResLang("IDS_OPT_SHRINK_TO_FIT", "縮小して全体を表示する");
	extfun.setResLang("IDS_OPT_PASSWORD2", "パスワードの確認");
	extfun.setResLang("IDS_OPT_DM_BARCODE", "DataMatrixコード");
	extfun.setResLang("IDS_OPT_FONT_STYLE_COLON", "フォント スタイル：");
	extfun.setResLang("IDS_OPT_COLOR_COLON", "色：");
	extfun.setResLang("IDS_OPT_INTERVAL_COLON", "字間：");
	extfun.setResLang("IDS_OPT_STRETCH_COLON", "Stretch :");
	extfun.setResLang("IDS_OPT_EFFECT", "飾り");
	extfun.setResLang("IDS_OPT_UNDERLINE", "下線");
	extfun.setResLang("IDS_OPT_STRIKEOUT", "取り消し線");
	extfun.setResLang("IDS_OPT_DOUBLE_STRIKEOUT", "二重取り消し線");
	extfun.setResLang("IDS_OPT_NO_FILL", "塗りつぶしなし");
	extfun.setResLang("IDS_OPT_TRANSPARENCY", "透過度");
	extfun.setResLang("IDS_OPT_GRADIENT", "グラデーション");
	extfun.setResLang("IDS_OPT_USE_GRADIENT", "グラデーション使用");
	extfun.setResLang("IDS_OPT_SLASH", "スラッシュ");
	extfun.setResLang("IDS_OPT_BACK_SLASH", "逆スラッシュ");
	extfun.setResLang("IDS_OPT_START_POSITION", "開始位置");
	extfun.setResLang("IDS_OPT_FROM_EDGE", "段");
	extfun.setResLang("IDS_OPT_DIRECT", "正方向");
	extfun.setResLang("IDS_OPT_FROM_CENTER", "中央");
	extfun.setResLang("IDS_OPT_REVERSE", "逆方向");
	extfun.setResLang("IDS_OPT_THICKNESS_W", "太さ(W) :");
	extfun.setResLang("IDS_OPT_STYLE_Y", "スタイル(Y) :");
	extfun.setResLang("IDS_OPT_COLOR_C", "色(C) :");
	extfun.setResLang("IDS_OPT_CLIPPING", "クリッピング");
	extfun.setResLang("IDS_OPT_WORD_WRAP", "自動改行");
	extfun.setResLang("IDS_OPT_WORD_WRAP_TYPE", "自動改行タイプ");
	extfun.setResLang("IDS_OPT_IGNORE_SPACE", "空白無視");
	extfun.setResLang("IDS_OPT_NON_ASCII_WORD", "単語の途中で改行を防止");
	extfun.setResLang("IDS_OPT_TOOLTIP_TEXT", "ツールヒント テキスト...");
	extfun.setResLang("IDS_OPT_BASIC", "Basic");
	extfun.setResLang("IDS_OPT_OUTLINE", "Outline");
	extfun.setResLang("IDS_OPT_3D", "3D");
	extfun.setResLang("IDS_OPT_ENGRAVE", "Engrave");
	extfun.setResLang("IDS_OPT_SEGMENT", "Segments");
	extfun.setResLang("IDS_OPT_HOLLOW", "Hollow");
	extfun.setResLang("IDS_OPT_SHADOW", "Shadow");
	extfun.setResLang("IDS_OPT_IMAGE_STYLE", "スタイル：");
	extfun.setResLang("IDS_OPT_BARCODE_STYLE", "スタイル ：");
	extfun.setResLang("IDS_OPT_DATA_GAP", "データの間隔 ：");
	extfun.setResLang("IDS_OPT_DATA_POSITION", "データの位置 ：");
	extfun.setResLang("IDS_OPT_BARCODE_MARGIN", "バーコードの余白 ：");
	extfun.setResLang("IDS_OPT_ALIGN_HORIZONTALLY", "横方向揃え ：");
	extfun.setResLang("IDS_OPT_RATION_COLON", "バーの比率 ：");
	extfun.setResLang("IDS_OPT_PRINTING_SCALE", "印刷時、拡大/縮小 ：");
	extfun.setResLang("IDS_OPT_ROTATION_COLON", "回転 ：");
	extfun.setResLang("IDS_OPT_TITLE_GAP", "タイトルの間隔 ：");
	extfun.setResLang("IDS_OPT_TITLE_POSITION", "タイトルの位置 ：");
	extfun.setResLang("IDS_OPT_BARCODE_ERROR_OPTION", "エラー表示オプション :");
	extfun.setResLang("IDS_OPT_DISPLAY_ERROR_DATA", "エラー データ表示");
	extfun.setResLang("IDS_OPT_DISPLAY_ERROR_SIZE", "バーコードのサイズ エラー表示");
	extfun.setResLang("IDS_OPT_DISPLAY_EMPTY_DATA", "空白値表示");
	extfun.setResLang("IDS_OPT_PDF_IMAGE_STYLE", "イメージのスタイル：");
	extfun.setResLang("IDS_OPT_PDF_ROW_NUMBER", "行数：");
	extfun.setResLang("IDS_OPT_PDF_COL_NUMBER", "列数：");
	extfun.setResLang("IDS_OPT_PDF_ECC", "誤り訂正符号数：");
	extfun.setResLang("IDS_OPT_PDF_X_SCALE", "Xのサイズ：");
	extfun.setResLang("IDS_OPT_PDF_Y_SCALE", "Yのサイズ：");
	extfun.setResLang("IDS_OPT_BORDER_COLOR", "枠線色 :");
	extfun.setResLang("IDS_OPT_BORDER_TRANSPARENCY", "Border Transparency :");
	extfun.setResLang("IDS_OPT_FILL_COLOR", "塗りつぶし色 :");
	extfun.setResLang("IDS_OPT_THICKNESS", "線の太さ :");
	extfun.setResLang("IDS_OPT_SHAPE_NO_FILL", "透過 :");
	extfun.setResLang("IDS_OPT_LINE_TYPE", "線のタイプ :");
	extfun.setResLang("IDS_OPT_TOOLTIP_TEXT_COLON", "ツールヒント テキスト :");
	extfun.setResLang("IDS_OPT_EDIT_CHART", "チャート編集");
	extfun.setResLang("IDS_OPT_SHOW_DATA", "データ表示");
	extfun.setResLang("IDS_OPT_EDIT_SHAPE", "図形編集");
	extfun.setResLang("IDS_FORCS_RV", "Forcs(R) OZ Report Viewer");
	extfun.setResLang("IDS_OPT_EXCEL_LINE", "行");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE_TYPE", "保存形式");
	extfun.setResLang("IDS_OPT_JPG_ZOOM_INOUT", "拡大/縮小の比率 ");
	extfun.setResLang("IDS_OPT_ZOOM_INOUT_COLON", "拡大/縮小の比率 : ");
	extfun.setResLang("IDS_OPT_QUALITY_COLON", "品質 : ");
	extfun.setResLang("IDS_OPT_TIFF_SIZE", "サイズ");
	extfun.setResLang("IDS_OPT_PAGELINE", "行");
	extfun.setResLang("IDS_OPT_WORD_BAND_SAVE_PAGE", "ページ ヘッダー/フッター バンドをヘッダー/フッターに保存");
	extfun.setResLang("IDS_OPT_PRINT_MULTIDOC", "マルチ レポート");
	extfun.setResLang("ID_PAGE_CONTROL_WINDOW", "ページ選択");
	extfun.setResLang("IDS_OPT_FONT_NAME_COLON", "フォント：");
	extfun.setResLang("IDS_OPT_FONT_OPTION", "オプション");
	extfun.setResLang("IDS_OPT_AUTO_SELECTED", "次のページ数に合わせる");
	extfun.setResLang("IDS_OPT_SIDE", "横");
	extfun.setResLang("IDS_OPT_LENGTH", "縦");
	extfun.setResLang("IDS_OPT_OTHER", "その他");
	extfun.setResLang("IDS_OPT_FONT_SAVE_WAY", "保存方式");
	extfun.setResLang("IDS_OPT_HORIZONTAL_NAVI", "水平");
	extfun.setResLang("IDS_OPT_VERTICAL_NAVI", "垂直");
	extfun.setResLang("IDS_OPT_PNG_SAVE", "PNG保存の設定");
	extfun.setResLang("IDS_OPT_GIF_SAVE", "GIF保存の設定");
	extfun.setResLang("IDS_OPT_REMOVE_LINES", "行の削除");
	extfun.setResLang("IDS_OPT_ENCODING_HDM", "エンコード：");
	extfun.setResLang("IDS_OPT_SVG_SAVE", "SVG 保存の設定");
	extfun.setResLang("IDS_OPT_PDF_CHANGEABLE", "変更を許可");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE1", "なし");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE2", "注釈の作成、フォームフィールドの入力と既存の署名フィールドに署名");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE3", "ページレイアウト、フォームフィールドの入力と既存の署名フィールドに署名");
	extfun.setResLang("IDS_OPT_PDF_RADIO_CHANGEABLE4", "ページの抽出を除くすべての操作");
	extfun.setResLang("IDS_OPT_SAVE_WAY_BASE", "保存形式");
	extfun.setResLang("IDS_OPT_SAVE_LARGEBUNDLE_BYPAGE", "レポートを1ページでバインディングしてから保存し");
	extfun.setResLang("IDS_OPT_SAVE_LARGE_BUNDLE", "1ページで保存");
	extfun.setResLang("IDS_OPT_SAVE_BY_PAGE", "ページごとに保存");
	extfun.setResLang("IDS_OPT_KEEP_SAVING", "keep saving");
	extfun.setResLang("IDC_TITLE_SECURITY", "読み取りパスワード");
	extfun.setResLang("IDC_EDIT_PASSWORD", "パスワード");
	extfun.setResLang("IDC_EDIT_PASSWORD_VERIFY", "パスワードの確認");
	extfun.setResLang("IDC_ZIP_GROUP", "圧縮");
	extfun.setResLang("IDC_COMPRESS_ON_SAVE", "圧縮保存");
	extfun.setResLang("IDC_PAPER_SETUP", "用紙設定");
	extfun.setResLang("IDC_CHECK_ADJUST", "用紙に合わせて印刷");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE_DETAIL", "ページ番号をカンマで区切って指定するか、ページ範囲を指定してください。");
	extfun.setResLang("IDS_OPT_CHOOSEPAGE_DETAIL2", "例）1,3,5-12");
	extfun.setResLang("IDS_OPT_NEXCEL_SAVE", "Nexcel保存の設定");
	extfun.setResLang("IDS_OPT_NEXCEL_SAVE2", "Nexcel保存の設定(詳細設定)");
	extfun.setResLang("IDS_OPT_EXCEL_SAVE2", "Excel保存の設定(詳細設定)");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM", "比率");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM_RATIO", "拡大/縮小比率: ");
	extfun.setResLang("IDS_CHECK_EXCEL_ZOOM_RATIO2", "拡大/縮小比率(%)");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES", "ウィンドウ枠の固定");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_ROW", "行: ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_COL", "列: ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_ROW_M", "行 ");
	extfun.setResLang("IDS_CHECK_EXCEL_FREEZEPANES_COL_M", "列 ");
	extfun.setResLang("IDC_EDIT_ZIP_PASSWORD", "パスワード");
	extfun.setResLang("IDC_EDIT_ZIP_PASSWORD_VERIFY", "パスワードの確認");
	extfun.setResLang("IDS_OPT_BMP_SAVE", "BMP保存の設定");
	extfun.setResLang("IDS_OPT_RTF_SAVE", "RTF保存の設定");
	extfun.setResLang("IDS_OPT_SELECTREPORT", "レポート指定:");
	extfun.setResLang("IDS_OPT_SELECTREPORT2", "レポート選択...");
	extfun.setResLang("IDS_OPT_SELECTREPORT_TITLE", "レポート選択");
	extfun.setResLang("IDS_OPT_CHECK_SELECT_ALL", "すべて選択");
	extfun.setResLang("ID_PAGE_CONTROL_NAVIGATOR", "ページ選択");
	extfun.setResLang("ID_PARAMETER_TOOLBAR", "照会ツールバー");
	extfun.setResLang("IDS_OPT_ENCODING_JPG", "JPG");
	extfun.setResLang("IDS_OPT_MARGIN_COLON", "余白 :");
	extfun.setResLang("IDS_OPT_SEARCH", "検索");
	extfun.setResLang("IDS_CONSOLE", "コンソール");
	extfun.setResLang("IDS_LICENSE_ERROR_TITLE", "ライセンスの検証が失敗しました。");
	extfun.setResLang("IDS_LICENSE_ERROR_EXPIRED", "ライセンスの期限が切れました。");
	extfun.setResLang("IDS_LICENSE_ERROR_VERSION", "製品のバージョンが一致しません。");
	extfun.setResLang("IDS_LICENSE_ERROR_CERT", "証明書の検証に失敗しました。");
	extfun.setResLang("IDS_LICENSE_ERROR_FILENOTFOUND", "ライセンスファイルが見つかりません。");
	extfun.setResLang("IDS_LICENSE_ERROR_DOMAIN", "The license does not match with software domain.");
	extfun.setResLang("IDS_OPT_CELL_SAVE", "Cell保存の設定");
	extfun.setResLang("IDS_OPT_CELL_SAVE2", "Cell保存の設定(詳細設定)");
	extfun.setResLang("IDS_SELECT_FILE", "ファイル");
	extfun.setResLang("IDS_SHOOT", "カメラ");
	extfun.setResLang("IDS_SHOOT_OR_SELECT_FILE", "カメラ/ファイル選択");
	extfun.setResLang("IDS_IMAGE_MERGE_ITEM", "写真の結合");
	extfun.setResLang("IDS_IMAGE_EDIT_TITLE", "写真編集");
	extfun.setResLang("IDS_IMAGE", "写真");
	extfun.setResLang("IDS_IMAGE_EDIT_DONE", "完了");
	extfun.setResLang("IDS_IMAGE_EDIT_CANCEL", "キャンセル");
	extfun.setResLang("IDS_IMAGE_EDIT_ROTATE", "回転");
	extfun.setResLang("IDS_IMAGE_EDIT_FILL", "画面に合わせる");
	extfun.setResLang("IDS_IMAGE_EDIT_FIT", "幅に合わせる");
	extfun.setResLang("IDS_DLG_EDIT", "編集");
	extfun.setResLang("IDS_THUMBNAIL_ALLOWCLOSE", "閉じる");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_LEFT", "左揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_CENTER", "左右中央揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_RIGHT", "右揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_HDIST", "左右揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_HJUSTIFY", "左右両端揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_TOP", "上揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_MIDDLE", "上下中央揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_BOTTOM", "下揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_VDIST", "上下揃え");
	extfun.setResLang("IDS_FORMAT_JUSTIFY_VJUSTIFY", "上下両端揃え");
	extfun.setResLang("IDS_LAYOUT_MOVE_LEFT", "テキスト方向 左へ");
	extfun.setResLang("IDS_LAYOUT_MOVE_TOP", "テキスト方向 上側");
	extfun.setResLang("IDS_LAYOUT_MOVE_RIGHT", "テキスト方向 右へ");
	extfun.setResLang("IDS_LAYOUT_MOVE_BOTTOM", "テキスト方向 下側");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_HORIZONTAL", "HORIZONTAL");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_VERTICAL", "VERTICAL");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_CLOCKWISE", "CLOCKWISE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_COUNTERCLOCKWISE", "COUNTERCLOCKWISE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_VERTICAL_2BYTE", "VERTICAL_2BYTE");
	extfun.setResLang("IDS_PI_LABEL_STRETCHTYPE_HORIZONTAL_2BYTE", "HORIZONTAL_2BYTE");
	extfun.setResLang("IDS_BORDER_TOP", "上側枠");
	extfun.setResLang("IDS_BORDER_MIDDLE", "内側横枠");
	extfun.setResLang("IDS_BORDER_BOTTOM", "下側枠");
	extfun.setResLang("IDS_BORDER_LEFT", "左側枠");
	extfun.setResLang("IDS_BORDER_CENTER", "内側縦枠");
	extfun.setResLang("IDS_BORDER_EMPTY", "枠なし");
	extfun.setResLang("IDS_BORDER_RIGHT", "右側枠");
	extfun.setResLang("IDS_BORDER_ALL", "全ての枠");
	extfun.setResLang("IDS_BORDER_OUTSIDE", "外側枠");
	extfun.setResLang("IDS_BORDER_INSIDE", "内側枠");
	extfun.setResLang("IDS_BORDER_USER", "ユーザー指定");
	extfun.setResLang("ID_TITLEBAR_THUMBNAIL_TITLE", "ページのサムネール");
	extfun.setResLang("ID_TITLEBAR_TREE_TITLE", "ツリー");
	extfun.setResLang("IDS_SEAL_DESCRIPTION", "Please align the seal recognition area with the green guidelines.");
	extfun.setResLang("IDS_DIALOG_FORMAT", "書式");
	extfun.setResLang("IDS_SIGNEX_SIGN", "署名入力");
	extfun.setResLang("IDS_SIGNEX_SEAL", "印鑑スキャン");
	extfun.setResLang("IDS_ATTACHMENTS_FILE_SIZE_LIMIT", "最大ファイルサイズ: %s/件");
	extfun.setResLang("IDS_ATTACHMENTS_SUMMARY_TITLE", "ファイルリスト");
	extfun.setResLang("IDS_ATTACHMENTS_COUNT", "添付ファイル数");
	extfun.setResLang("IDS_ATTACHMENTS_SELECT", "ファイルを選択");
	extfun.setResLang("IDS_ATTACHMENTS_APPEND", "ファイルを追加");
	extfun.setResLang("IDS_ATTACHMENTS_DOWNLOAD", "ダウンロード");
	extfun.setResLang("IDS_ATTACHMENTS_DELETE", "削除");
	extfun.setResLang("IDS_ATTACHMENTS_EMPTY", "ここにファイルをドラッグ&ドロップ\n或は\n\"追加\"追加ボタンをクリック");
	extfun.setResLang("IDS_ATTACHMENTS_MAXSIZE", "最大サイズ(nMB)");
	extfun.setResLang("IDS_ATTACHMENTS_IMAGE_INDIVIDUALLY", "個別に添付");
	extfun.setResLang("IDS_ATTACHERROR_UNSUPPORTED", "サポートされていないファイル形式");
	extfun.setResLang("IDS_ATTACHERROR_OVERSIZE", "ファイルサイズ超過");
	extfun.setResLang("IDS_ATTACHERROR_OPENFAIL", "読み取り失敗");
	extfun.setResLang("IDS_ATTACHERROR_INVALID_PDF", "不明なPDFファイル");
	extfun.setResLang("IDS_ATTACHERROR_PASSWORD_PDF", "パスワードが設定されたPDFファイル");
	extfun.setResLang("IDS_SEAL_IMAGE_UPLOAD", "印影画像のアップロード");
	extfun.setResLang("IDS_SEAL_IMAGE_REUPLOAD", "印影画像の再アップロード");
	extfun.setResLang("IDS_SEAL_IMAGE_APPLY", "適用");
	extfun.setResLang("IDS_SCAN_SUCCESS", "印影画像の認識に成功しました。");
	extfun.setResLang("IDS_SCAN_FAIL", "印影画像を認識できません。");
	extfun.setResLang("IDS_SCAN_RETRY", "改めて認識したい場合は再度スキャンし直してください。");
	extfun.setResLang("IDS_SCAN_REUPLOAD", "改めて選択したい場合は画像を再度アップロードし直してください。");
	extfun.setResLang("IDS_SCAN_RETRY_LINK", "再スキャン");
	extfun.setResLang("IDS_SCAN_REUPLOAD_LINK", "再アップロード");
	extfun.setResLang("IDS_SCAN_UPLOAD_FAIL", "もう一度画像をアップロードしてください。");
	extfun.setResLang("IDS_MSG_SCAN_WAITING", "画像を分析しています。少々お待ち下さい。");
	extfun.setResLang("IDS_OPT_FONT_STYLE", "スタイル");
	extfun.setResLang("IDS_OPT_COLOR", "色");
	extfun.setResLang("IDS_REMOVE_MEMO", "削除しますか？");
	extfun.setResLang("IDS_OPT_MEMO", "メモ");
	extfun.setResLang("IDS_OZVS_ERROR_PLAY", "ビデオ署名を実行することができません。");
	extfun.setResLang("IDS_OZVR_RECORD_COMPLETED", "録音が完了されました。");
	extfun.setResLang("IDS_OZVR_ERROR_PLAY", "プレイに失敗しました。");
	extfun.setResLang("IDS_SIGN_CONFIRM", "保存");
	extfun.setResLang("IDS_SIGN_RESET", "初期化");
	extfun.setResLang("IDS_SIGN_REUSABLE", "インポート");
}